import type React from 'react'

export const styles: Record<string, React.CSSProperties> = {

  buttonRow: {
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  checkboxGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(190px, 1fr))',
    gap: 8,
    margin: '8px 0 12px',
  },
  checkboxLabel: {
    display: 'flex',
    gap: 8,
    alignItems: 'flex-start',
    fontSize: 13,
    lineHeight: 1.35,
    color: '#173425',
  },
  smallDanger: {
    fontSize: 13,
    lineHeight: 1.45,
    color: '#8a2f2f',
  },
  warningBox: {
    border: '1px solid #d9b35f',
    background: '#fff8e8',
    color: '#5b410b',
    borderRadius: 14,
    padding: 14,
    margin: '14px 0 18px',
    lineHeight: 1.5,
  },
  reviewBox: {
    border: '1px solid #d7dfd3',
    background: '#fbfdf9',
    borderRadius: 18,
    padding: 18,
  },
  intakeFlow: {
    display: 'grid',
    gap: 14,
  },
  intakeStepCard: {
    border: '1px solid #d7dfd3',
    background: '#fbfcfa',
    borderRadius: 18,
    padding: 16,
  },
  intakeStepHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
    marginBottom: 12,
    color: '#173425',
  },
  intakeMediaGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: 10,
  },
  intakeMediaButton: {
    minHeight: 68,
    border: '1px solid #d7dfd3',
    background: '#ffffff',
    color: '#173425',
    borderRadius: 16,
    padding: 12,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    fontWeight: 900,
    cursor: 'pointer',
    lineHeight: 1.25,
  },
  hiddenFileInput: {
    position: 'absolute',
    opacity: 0,
    width: 1,
    height: 1,
    pointerEvents: 'none',
  },
  mediaSummaryBox: {
    display: 'grid',
    gap: 6,
    marginTop: 12,
    padding: 12,
    border: '1px solid #e5ecdf',
    background: '#ffffff',
    borderRadius: 14,
    color: '#5f6f63',
    fontSize: 14,
    lineHeight: 1.45,
  },
  propertyFactsSummary: {
    display: 'grid',
    gap: 6,
    padding: 12,
    border: '1px solid #dfe8da',
    background: '#ffffff',
    borderRadius: 14,
    color: '#173425',
    fontWeight: 800,
    lineHeight: 1.45,
  },
  progressiveFieldGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
    gap: 10,
    paddingTop: 10,
  },
  grid4: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: 12,
    alignItems: 'start',
  },
  applicationFilterGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(5, minmax(0, 1fr))',
    gap: 12,
    alignItems: 'start',
  },
  intakeDisclosure: {
    border: '1px solid #d7dfd3',
    background: '#ffffff',
    borderRadius: 16,
    padding: '0 12px 8px',
  },
  intakeStatusCard: {
    border: '1px solid #dfe8da',
    background: '#f7faf5',
    borderRadius: 18,
    padding: 16,
    color: '#173425',
  },
  intakeActionRow: {
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  scopeText: {
    whiteSpace: 'pre-wrap',
    lineHeight: 1.55,
    color: '#123524',
    background: '#f7faf5',
    border: '1px solid #dfe8da',
    borderRadius: 12,
    padding: 12,
  },
  segmentedControl: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: 6,
    padding: 5,
    border: '1px solid #d7dfd3',
    borderRadius: 16,
    background: '#f7faf5',
    margin: '16px 0',
  },
  segmentedButton: {
    border: 'none',
    background: 'transparent',
    color: '#5f6f63',
    borderRadius: 12,
    minHeight: 48,
    padding: '10px 8px',
    fontSize: 14,
    fontWeight: 900,
    cursor: 'pointer',
  },
  segmentedActive: {
    border: '1px solid #d7dfd3',
    background: '#ffffff',
    color: '#173425',
    borderRadius: 8,
    minHeight: 48,
    padding: '10px 8px',
    fontSize: 14,
    fontWeight: 900,
    cursor: 'pointer',
  },
  messageEmptyState: {
    border: '1px solid #dfe8da',
    background: '#fbfcfa',
    borderRadius: 18,
    padding: 18,
    color: '#5f6f63',
    lineHeight: 1.5,
  },
  messageCard: {
    background: '#ffffff',
    border: '1px solid #d7dfd3',
    borderRadius: 18,
    padding: 18,
    marginBottom: 12,
    maxWidth: 920,
  },
  messageCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    flexWrap: 'wrap',
  },
  messagePropertyTitle: {
    margin: 0,
    color: '#173425',
    fontSize: 21,
    lineHeight: 1.2,
    letterSpacing: 0,
  },
  messagePropertyMeta: {
    margin: '4px 0 0',
    color: '#7a857d',
    fontSize: 13,
    lineHeight: 1.3,
  },
  workflowStateChip: {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: 30,
    borderRadius: 8,
    background: '#eef6ec',
    color: '#0f542d',
    padding: '6px 10px',
    fontSize: 12,
    fontWeight: 900,
  },
  messagePurposeRow: {
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap',
    alignItems: 'center',
    marginTop: 12,
    color: '#5f6f63',
    fontSize: 13,
    lineHeight: 1.4,
  },
  messagePreview: {
    whiteSpace: 'pre-wrap',
    margin: '12px 0',
    color: '#273b2f',
    fontSize: 15,
    lineHeight: 1.5,
  },
  messageNote: {
    margin: '0 0 12px',
    color: '#5f6f63',
    fontSize: 13,
    lineHeight: 1.4,
  },
  messageActionRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(160px, auto) minmax(120px, 1fr)',
    gap: 10,
    alignItems: 'start',
  },
  messageMore: {
    minWidth: 0,
  },
  messageMoreSummary: {
    minHeight: 48,
    display: 'inline-flex',
    alignItems: 'center',
    padding: '0 14px',
    border: '1px solid #d7dfd3',
    borderRadius: 8,
    color: '#173425',
    background: '#ffffff',
    fontWeight: 900,
    cursor: 'pointer',
  },
  messageMoreGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
    gap: 8,
    marginTop: 8,
  },
  mutedList: {
    color: '#536056',
    lineHeight: 1.6,
    marginTop: 8,
  },
  replyDraftBox: {
    marginTop: 8,
    whiteSpace: 'pre-wrap',
    lineHeight: 1.55,
    background: '#f5f7fb',
    border: '1px solid #dce3ee',
    borderRadius: 12,
    padding: 12,
    color: '#1f2a30',
  },
  linkPanel: {
    border: '1px solid #cbd8ca',
    background: '#ffffff',
    borderRadius: 8,
    padding: 14,
    textAlign: 'left',
    cursor: 'pointer',
    color: '#173425',
    display: 'grid',
    gap: 6,
    lineHeight: 1.4,
  },
  propertyProfileCard: {
    border: '1px solid #cbd8ca',
    background: '#fbfdf9',
    borderRadius: 8,
    padding: 12,
    margin: '12px 0',
  },
  mobilePropertyProfileCard: {
    borderRadius: 20,
    padding: 14,
    background: '#fbfdf9',
  },
  compactFactGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(130px, 1fr))',
    gap: 8,
    marginTop: 10,
    fontSize: 13,
    color: '#36463b',
  },
  mobileCompactFactGrid: {
    gridTemplateColumns: '1fr',
    gap: 7,
    fontSize: 15,
  },
  intelligencePanel: {
    border: '1px solid #9fc6a7',
    background: '#f4fbf5',
    borderRadius: 8,
    padding: 16,
    margin: '16px 0',
  },
  workflowCard: {
    border: '1px solid #d7dfd3',
    background: '#fbfcfa',
    borderRadius: 14,
    padding: 16,
    margin: '16px 0',
  },
  mobileWorkflowCard: {
    padding: 14,
    borderRadius: 18,
  },
  workflowHeader: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: 16,
  },
  workflowStage: {
    display: 'inline-flex',
    alignItems: 'center',
    border: '1px solid #d7dfd3',
    background: '#ffffff',
    color: '#5f6f63',
    borderRadius: 8,
    padding: '5px 9px',
    fontSize: 12,
    fontWeight: 900,
  },
  workflowTitle: {
    margin: '10px 0 4px',
    color: '#173425',
    fontSize: 18,
    lineHeight: 1.25,
  },
  workflowBody: {
    margin: 0,
    color: '#4c5b50',
    fontSize: 14,
    lineHeight: 1.5,
  },
  workflowFootnote: {
    margin: '8px 0 0',
    color: '#7a857d',
    fontSize: 12,
    lineHeight: 1.4,
  },
  workflowPrimaryButton: {
    border: '1px solid #0f542d',
    background: '#0f542d',
    color: '#ffffff',
    padding: '13px 18px',
    borderRadius: 8,
    cursor: 'pointer',
    fontWeight: 900,
    minHeight: 48,
    minWidth: 168,
  },
  intelligenceSummary: {
    border: '1px solid #dfe8da',
    background: '#ffffff',
    borderRadius: 12,
    padding: 12,
    marginTop: 14,
  },
  logisticsAlert: {
    display: 'grid',
    gap: 6,
    marginTop: 10,
    padding: 10,
    border: '1px solid #ecd9a7',
    background: '#fff8e8',
    borderRadius: 10,
    color: '#6f4f14',
    fontSize: 12,
    lineHeight: 1.4,
  },
  logisticsSummaryBox: {
    borderTop: '1px solid #edf1ea',
    marginTop: 12,
    paddingTop: 12,
  },
  logisticsFactGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
    gap: 8,
    margin: '10px 0',
    color: '#5f6f63',
    fontSize: 13,
    fontWeight: 800,
    textTransform: 'capitalize',
  },
  workflowSecondaryButton: {
    border: '1px solid #d7dfd3',
    background: '#ffffff',
    color: '#173425',
    padding: '12px 14px',
    borderRadius: 8,
    cursor: 'pointer',
    fontWeight: 800,
    minHeight: 48,
    textAlign: 'left',
  },
  moreActions: {
    marginTop: 14,
  },
  moreActionsSummary: {
    cursor: 'pointer',
    color: '#0f542d',
    fontWeight: 900,
    minHeight: 44,
    display: 'flex',
    alignItems: 'center',
  },
  moreActionsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 10,
    paddingTop: 8,
  },
  agentOutputGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
    gap: 12,
    paddingTop: 8,
  },
  agentOutputCard: {
    border: '1px solid #d7dfd3',
    background: '#ffffff',
    borderRadius: 12,
    padding: 12,
  },
  packetBox: {
    whiteSpace: 'pre-wrap',
    background: '#ffffff',
    border: '1px solid #d7dfd3',
    borderRadius: 8,
    padding: 12,
    color: '#173425',
    fontFamily: 'Inter, Arial, sans-serif',
    fontSize: 13,
    lineHeight: 1.5,
  },
  page: {
    minHeight: '100vh',
    background: '#f6f4ef',
    color: '#173425',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Inter", "SF Pro Display", "Segoe UI", Arial, sans-serif',
    WebkitTextSizeAdjust: '100%' as any,
  },
  mobilePage: {
    background: '#f7f5f0',
    paddingBottom: 'calc(env(safe-area-inset-bottom) + 18px)',
  },
  header: {
    display: 'grid',
    gridTemplateColumns: '1fr 1.4fr 1fr',
    gap: 20,
    alignItems: 'center',
    padding: '28px 42px 18px',
  },
  mobileHeader: {
    display: 'grid',
    gridTemplateColumns: '1fr',
    gap: 12,
    padding: '18px 16px 10px',
    position: 'sticky',
    top: 0,
    zIndex: 20,
    background: 'rgba(247,245,240,0.96)',
    backdropFilter: 'blur(18px)',
    borderBottom: '1px solid rgba(15,84,45,0.08)',
  },
  brand: {
    fontSize: 30,
    letterSpacing: 3,
    fontWeight: 900,
    color: '#0f542d',
  },
  mobileBrand: {
    fontSize: 22,
    letterSpacing: 1.5,
  },
  subBrand: {
    marginTop: 8,
    fontSize: 12,
    letterSpacing: 5,
    fontWeight: 800,
    color: '#0f542d',
  },
  mobileSubBrand: {
    marginTop: 4,
    fontSize: 10,
    letterSpacing: 3,
  },
  nav: {
    display: 'flex',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 10,
  },
  mobileNav: {
    justifyContent: 'flex-start',
    flexWrap: 'nowrap',
    overflowX: 'auto',
    WebkitOverflowScrolling: 'touch' as any,
    paddingBottom: 4,
    marginLeft: -2,
    marginRight: -2,
  },
  navButton: {
    border: 'none',
    background: 'transparent',
    padding: '11px 14px',
    borderRadius: 999,
    fontWeight: 800,
    cursor: 'pointer',
    color: '#173425',
    minHeight: 44,
  },
  navActive: {
    border: '1px solid #0f542d',
    background: '#e7f3e5',
    padding: '11px 14px',
    borderRadius: 999,
    fontWeight: 900,
    cursor: 'pointer',
    color: '#0f542d',
    minHeight: 44,
  },
  mobileNavPill: {
    flex: '0 0 auto',
    padding: '11px 15px',
    minHeight: 48,
    whiteSpace: 'nowrap',
  },
  moreMenu: {
    position: 'absolute',
    top: 'calc(100% + 8px)',
    right: 0,
    minWidth: 250,
    maxHeight: 'min(70vh, 620px)',
    overflowY: 'auto' as any,
    background: '#ffffff',
    border: '1px solid #d8cfc4',
    borderRadius: 8,
    boxShadow: '0 8px 18px rgba(0,0,0,0.10)',
    padding: 8,
    zIndex: 100,
  },
  moreMenuLabel: {
    padding: '10px 12px 6px',
    color: '#5f6f63',
    fontSize: 12,
    fontWeight: 900,
    textTransform: 'uppercase' as any,
  },
  moreMenuItem: {
    width: '100%',
    textAlign: 'left' as any,
    padding: '12px 14px',
    border: 'none',
    borderRadius: 10,
    background: '#ffffff',
    color: '#123225',
    fontWeight: 800,
    cursor: 'pointer',
    minHeight: 48,
  },
  moreMenuItemActive: {
    width: '100%',
    textAlign: 'left' as any,
    padding: '12px 14px',
    border: 'none',
    borderRadius: 10,
    background: '#e8f5eb',
    color: '#123225',
    fontWeight: 900,
    cursor: 'pointer',
    minHeight: 48,
  },
  headerActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 10,
    flexWrap: 'wrap',
  },
  mobileHeaderActions: {
    justifyContent: 'stretch',
  },
  main: {
    padding: '12px 42px 60px',
  },
  mobileMain: {
    padding: '12px 14px calc(env(safe-area-inset-bottom) + 28px)',
  },
  previewBanner: {
    margin: '0 42px 18px',
    padding: '14px 18px',
    border: '1px solid #d9b35f',
    borderRadius: 16,
    background: '#fff8e8',
    color: '#5b410b',
    lineHeight: 1.45,
  },
  twoColumn: {
    display: 'grid',
    gridTemplateColumns: '1fr 0.45fr',
    gap: 22,
  },
  card: {
    background: 'white',
    border: '1px solid #d7dfd3',
    borderRadius: 8,
    padding: 20,
    boxShadow: 'none',
    marginBottom: 16,
  },
  mobileCard: {
    borderRadius: 8,
    padding: 16,
    marginBottom: 12,
    boxShadow: 'none',
  },
  sideCard: {
    background: '#eef3ea',
    border: '1px solid #d7dfd3',
    borderRadius: 8,
    padding: 20,
    alignSelf: 'start',
  },
  healthGrid: {
    display: 'grid',
    gap: 10,
    margin: '12px 0 16px',
  },
  healthRow: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 12,
    alignItems: 'center',
    background: '#ffffff',
    border: '1px solid #d7dfd3',
    borderRadius: 12,
    padding: '10px 12px',
  },
  healthOk: {
    color: '#0f542d',
  },
  healthNeedsSetup: {
    color: '#8a5b00',
  },
  dashboardHero: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 18,
    marginBottom: 18,
  },
  dashboardMetricGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4,minmax(0,1fr))',
    gap: 12,
    marginBottom: 18,
  },
  dashboardMetricCard: {
    border: '1px solid #d7dfd3',
    background: '#fbfcfa',
    borderRadius: 14,
    padding: 14,
    display: 'grid',
    gap: 4,
  },
  queueSnapshot: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 18,
  },
  queueSnapshotPill: {
    border: '1px solid #e5dfd3',
    background: '#fbfcfa',
    borderRadius: 8,
    padding: '8px 10px',
    color: '#5f6f63',
    fontSize: 13,
    fontWeight: 800,
  },
  hero: {
    background: '#173425',
    color: 'white',
    padding: 24,
    borderRadius: 8,
    fontSize: 30,
    fontWeight: 900,
    marginBottom: 18,
  },
  muted: {
    color: '#5f6f63',
    lineHeight: 1.5,
  },
  small: {
    color: '#5f6f63',
    fontSize: 14,
    lineHeight: 1.4,
  },
  smallList: {
    color: '#5f6f63',
    fontSize: 14,
    lineHeight: 1.5,
    paddingLeft: 18,
  },
  input: {
    width: '100%',
    minHeight: 52,
    padding: '14px 16px',
    borderRadius: 8,
    border: '1px solid #d7dfd3',
    marginBottom: 12,
    boxSizing: 'border-box',
    fontSize: 16,
    color: '#173425',
    background: '#ffffff',
  },
  grid2: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2,minmax(0,1fr))',
    gap: 12,
  },
  grid3: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3,minmax(0,1fr))',
    gap: 12,
  },
  grid5: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit,minmax(120px,1fr))',
    gap: 10,
    marginBottom: 12,
  },
  mobileStack: {
    display: 'grid',
    gridTemplateColumns: '1fr',
    gap: 12,
  },
  propertyInfoPanel: {
    border: '1px solid #d7dfd3',
    background: '#fbfcfa',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  factCard: {
    border: '1px solid #d7dfd3',
    background: '#f7faf5',
    borderRadius: 14,
    padding: 12,
    display: 'grid',
    gap: 4,
    color: '#173425',
  },
  uploadBox: {
    border: '1px solid #d7dfd3',
    borderRadius: 16,
    padding: 16,
    background: '#fbfcfa',
    marginBottom: 12,
  },
  primaryButton: {
    border: 'none',
    background: '#0f542d',
    color: 'white',
    padding: '13px 18px',
    borderRadius: 8,
    cursor: 'pointer',
    fontWeight: 900,
    minHeight: 48,
  },
  outlineButton: {
    border: '1px solid #d7dfd3',
    background: 'white',
    color: '#173425',
    padding: '13px 18px',
    borderRadius: 8,
    cursor: 'pointer',
    fontWeight: 900,
    minHeight: 48,
  },
  secondaryButton: {
    border: '1px solid #d7dfd3',
    background: '#f8faf7',
    color: '#173425',
    padding: '10px 14px',
    borderRadius: 8,
    cursor: 'pointer',
    fontWeight: 800,
    minHeight: 48,
  },
  wideButton: {
    width: '100%',
    border: 'none',
    background: '#0f542d',
    color: 'white',
    padding: '13px 18px',
    borderRadius: 8,
    cursor: 'pointer',
    fontWeight: 900,
    marginTop: 10,
    minHeight: 50,
  },
  success: {
    background: '#e7f3e5',
    color: '#0f542d',
    padding: 14,
    borderRadius: 14,
    marginBottom: 16,
    fontWeight: 800,
  },
  kanban: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr)',
    gap: 18,
  },
  mobileKanban: {
    gap: 14,
  },
  column: {
    borderRadius: 8,
    padding: 16,
    minHeight: 0,
  },
  mobileColumn: {
    borderRadius: 8,
    padding: 12,
  },
  empty: {
    background: 'rgba(255,255,255,0.8)',
    borderRadius: 14,
    padding: 14,
    color: '#5f6f63',
  },
  requestCard: {
    background: '#fffdfa',
    border: '1px solid #e3e0d8',
    borderRadius: 8,
    padding: 20,
    marginBottom: 18,
    maxWidth: 780,
    boxShadow: '0 10px 30px rgba(23, 52, 37, 0.04)',
  },
  propertyCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 14,
    flexWrap: 'wrap',
  },
  propertyTitleBlock: {
    display: 'grid',
    gap: 8,
    minWidth: 0,
    flex: 1,
  },
  propertyCardTitle: {
    color: '#173425',
    fontSize: 22,
    lineHeight: 1.2,
    fontWeight: 900,
    letterSpacing: 0,
  },
  propertySummaryLine: {
    color: '#4c5b50',
    fontSize: 15,
    lineHeight: 1.45,
    margin: 0,
    maxWidth: 620,
  },
  propertyMetaLine: {
    color: '#7a857d',
    fontSize: 13,
    lineHeight: 1.35,
    margin: 0,
  },
  propertyFlagRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  propertyFlag: {
    border: '1px solid #e5dfd3',
    background: '#ffffff',
    borderRadius: 8,
    color: '#4c5b50',
    padding: '6px 9px',
    fontSize: 12,
    fontWeight: 900,
  },
  propertyFlagMuted: {
    border: '1px solid #edf1ea',
    background: '#fbfcfa',
    borderRadius: 8,
    color: '#7a857d',
    padding: '6px 9px',
    fontSize: 12,
    fontWeight: 800,
  },
  nextActionPanel: {
    background: '#f8f7f3',
    border: '1px solid #e8e4dc',
    borderRadius: 8,
    padding: 16,
    marginTop: 16,
    marginBottom: 10,
    display: 'grid',
    gap: 12,
  },
  nextActionHeader: {
    display: 'grid',
    gap: 4,
  },
  nextActionTitle: {
    color: '#173425',
    fontSize: 16,
    fontWeight: 900,
    lineHeight: 1.3,
  },
  layerStack: {
    display: 'grid',
    gap: 8,
    marginTop: 12,
  },
  propertyLayer: {
    borderTop: '1px solid #edf1ea',
  },
  propertyLayerSummary: {
    minHeight: 54,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    cursor: 'pointer',
    color: '#173425',
    fontWeight: 900,
    listStyle: 'none',
  },
  propertyLayerHint: {
    display: 'block',
    color: '#7a857d',
    fontSize: 12,
    fontWeight: 700,
    marginTop: 3,
  },
  propertyLayerCount: {
    border: '1px solid #e5dfd3',
    borderRadius: 8,
    color: '#5f6f63',
    background: '#ffffff',
    padding: '5px 8px',
    fontSize: 12,
    fontWeight: 900,
    flex: '0 0 auto',
  },
  propertyLayerBody: {
    padding: '0 0 14px',
  },
  calmActionRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 10,
    alignItems: 'center',
  },
  mobileRequestCard: {
    borderRadius: 8,
    padding: 16,
    maxWidth: 'none',
    marginBottom: 12,
    boxShadow: 'none',
  },
  mobileRequestTitle: {
    display: 'block',
    fontSize: 20,
    lineHeight: 1.2,
    marginBottom: 6,
    letterSpacing: 0,
  },
  fileGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit,minmax(260px,1fr))',
    gap: 14,
  },
  fileBox: {
    background: '#fbfcfa',
    border: '1px solid #d7dfd3',
    borderRadius: 14,
    padding: 14,
  },
  fileActionRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto auto',
    alignItems: 'center',
    gap: 12,
    padding: '10px 0',
    borderBottom: '1px solid #edf1ea',
  },
  mobileFileActionRow: {
    gridTemplateColumns: '1fr',
    gap: 8,
    padding: '12px 0',
  },
  fileName: {
    color: '#173425',
    fontSize: 14,
    fontWeight: 800,
    overflowWrap: 'anywhere',
    minWidth: 0,
  },
  mediaPanel: {
    background: 'transparent',
    border: 'none',
    borderRadius: 8,
    padding: 0,
    marginTop: 10,
    marginBottom: 10,
  },
  mediaPanelHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 12,
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    marginBottom: 10,
  },
  mediaGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit,minmax(260px,1fr))',
    gap: 12,
  },
  mediaItem: {
    display: 'grid',
    gridTemplateColumns: '72px minmax(0, 1fr)',
    gap: 12,
    alignItems: 'start',
    background: '#fffdfa',
    border: '1px solid #e8e4dc',
    borderRadius: 12,
    padding: 10,
  },
  compactMetaGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
    gap: 8,
    color: '#5f625b',
    fontSize: 13,
    lineHeight: 1.4,
  },
  thumbnailButton: {
    border: 'none',
    background: 'transparent',
    padding: 0,
    cursor: 'pointer',
  },
  mediaThumbnail: {
    width: 72,
    height: 72,
    objectFit: 'cover',
    borderRadius: 8,
    border: '1px solid #d7dfd3',
    display: 'block',
    background: '#edf1ea',
  },
  mediaThumbnailFallback: {
    width: 72,
    height: 72,
    borderRadius: 8,
    border: '1px solid #d7dfd3',
    background: '#edf1ea',
    display: 'grid',
    placeItems: 'center',
    color: '#5f6f63',
    fontSize: 12,
    fontWeight: 800,
  },
  documentIcon: {
    width: 72,
    height: 72,
    borderRadius: 8,
    border: '1px solid #d7dfd3',
    background: '#f4f1ec',
    display: 'grid',
    placeItems: 'center',
    color: '#173425',
    fontSize: 12,
    fontWeight: 900,
  },
  mediaMeta: {
    display: 'grid',
    gap: 4,
    minWidth: 0,
  },
  mediaActions: {
    gridColumn: '1 / -1',
    display: 'flex',
    flexWrap: 'wrap',
    gap: 12,
    alignItems: 'center',
  },
  revealCard: {
    background: '#ffffff',
    border: '1px solid #d7dfd3',
    borderRadius: 14,
    marginTop: 12,
    overflow: 'hidden',
  },
  revealSummary: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 12,
    alignItems: 'center',
    minHeight: 56,
    padding: '14px 14px',
    cursor: 'pointer',
    listStyle: 'none',
    color: '#173425',
  },
  revealChevron: {
    flex: '0 0 auto',
    minHeight: 38,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    background: '#eef6ec',
    color: '#0f542d',
    padding: '8px 12px',
    fontSize: 12,
    fontWeight: 900,
  },
  revealBody: {
    borderTop: '1px solid #edf1ea',
    padding: 14,
  },
  revealAction: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 12,
  },
  revealItemList: {
    display: 'grid',
    gap: 8,
    marginBottom: 12,
  },
  revealLineItem: {
    display: 'grid',
    gap: 4,
    background: '#fbfcfa',
    border: '1px solid #edf1ea',
    borderRadius: 10,
    padding: 10,
  },
  questionList: {
    margin: 0,
    paddingLeft: 20,
    display: 'grid',
    gap: 8,
    color: '#173425',
    lineHeight: 1.45,
  },
  linkButton: {
    display: 'block',
    border: 'none',
    background: 'transparent',
    color: '#0f542d',
    padding: '4px 0',
    fontWeight: 800,
    cursor: 'pointer',
    textDecoration: 'underline',
  },
  mobileLinkButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
    padding: '10px 12px',
    borderRadius: 14,
    background: '#eef6ec',
    textDecoration: 'none',
  },
  badgeRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
    alignItems: 'center',
    marginBottom: 12,
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: 30,
    borderRadius: 8,
    background: '#e8efe4',
    color: '#274331',
    padding: '6px 10px',
    fontSize: 12,
    fontWeight: 900,
    textTransform: 'capitalize',
  },
  badgeMuted: {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: 30,
    borderRadius: 8,
    background: '#f1eee8',
    color: '#5f625b',
    padding: '6px 10px',
    fontSize: 12,
    fontWeight: 800,
    textTransform: 'capitalize',
  },
  badgeDanger: {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: 30,
    borderRadius: 8,
    background: '#f1e3dc',
    color: '#7a3b2d',
    padding: '6px 10px',
    fontSize: 12,
    fontWeight: 900,
    textTransform: 'capitalize',
  },
  noticeBox: {
    background: '#f8f5ee',
    border: '1px solid #e5dfd3',
    borderRadius: 8,
    padding: 10,
    marginTop: 10,
    marginBottom: 10,
    color: '#3d423b',
    fontSize: 12,
    lineHeight: 1.45,
  },
  aiBox: {
    background: '#f7f6f1',
    border: '1px solid #e5dfd3',
    borderRadius: 8,
    padding: 12,
    marginTop: 12,
  },
  inspectionTaskPanel: {
    background: '#fffdfa',
    border: '1px solid #e5dfd3',
    borderRadius: 8,
    padding: 14,
    marginTop: 14,
    marginBottom: 14,
  },
  inspectionTaskGrid: {
    display: 'grid',
    gap: 12,
  },
  inspectionTaskCard: {
    background: '#fffdfa',
    border: '1px solid #e8e4dc',
    borderRadius: 8,
    padding: 14,
    display: 'grid',
    gap: 12,
  },
  siteMediaPanel: {
    background: 'transparent',
    border: 'none',
    borderRadius: 8,
    padding: 14,
    marginTop: 14,
    marginBottom: 14,
  },
  siteMediaSourceList: {
    display: 'grid',
    gap: 8,
    marginTop: 8,
    marginBottom: 14,
  },
  siteMediaSourceRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto auto auto',
    gap: 10,
    alignItems: 'center',
    padding: '8px 0',
    borderBottom: '1px solid #edf1ea',
  },
  siteMediaFindingGrid: {
    display: 'grid',
    gap: 12,
    marginTop: 8,
  },
  siteMediaFindingCard: {
    background: '#fffdfa',
    border: '1px solid #e8e4dc',
    borderRadius: 8,
    padding: 14,
  },
  divider: {
    border: 'none',
    borderTop: '1px solid #d7dfd3',
    margin: '22px 0',
  },
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.45)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    zIndex: 1000,
  },
  modal: {
    width: '100%',
    maxWidth: 420,
    background: 'white',
    borderRadius: 20,
    padding: 24,
  },
}
