-- Shelter Prep full manual SQL regenerated for bigint public.properties(id)

-- Paste into Supabase SQL Editor as one script.

DO $$
BEGIN
  IF to_regclass('public.properties') IS NOT NULL AND NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'properties'
      AND column_name = 'id'
      AND data_type = 'bigint'
  ) THEN
    RAISE EXCEPTION 'Expected public.properties.id to be bigint before running Shelter Prep manual SQL';
  END IF;
END $$;


-- ============================================================================
-- Source: Caude may 17th/5.18.2026/002_property_foundation_fixed.sql
-- ============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- Shelter Prep — Property foundation migration (CORRECTED)
-- 002_property_foundation_fixed.sql
-- Uses `leads` table (the actual app table), not `work_requests`
-- Run after 001_ml_improvements.sql
-- ─────────────────────────────────────────────────────────────────────────────

BEGIN;

-- ── 1. PROPERTIES ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS properties (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at          timestamptz NOT NULL DEFAULT NOW(),
  updated_at          timestamptz NOT NULL DEFAULT NOW(),
  created_by          text,

  canonical_address   text NOT NULL,
  street_line_1       text NOT NULL,
  street_line_2       text,
  city                text NOT NULL,
  state               char(2) NOT NULL,
  zip                 char(5) NOT NULL,
  zip4                char(4),

  property_type       text,
  year_built          text,
  square_feet         text,
  bedrooms            text,
  bathrooms           text,
  lot_size            text,
  parcel_number       text,
  jurisdiction        text,
  zoning              text,

  match_confidence    text NOT NULL DEFAULT 'high'
                        CHECK (match_confidence IN ('high','medium','low')),
  needs_review        boolean NOT NULL DEFAULT false,
  review_reason       text,
  notes               text,

  CONSTRAINT uq_canonical_address UNIQUE (canonical_address)
);

CREATE INDEX IF NOT EXISTS idx_properties_zip         ON properties (zip);
CREATE INDEX IF NOT EXISTS idx_properties_needs_review ON properties (needs_review) WHERE needs_review = true;

-- ── 2. FK on leads (the actual app table) ─────────────────────────────────────

ALTER TABLE leads
  ADD COLUMN IF NOT EXISTS property_id bigint REFERENCES properties(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_leads_property_id ON leads (property_id);

-- ── 3. MAINTENANCE EVENTS ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS maintenance_events (
  id                        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id bigint NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  lead_id                   uuid REFERENCES leads(id) ON DELETE SET NULL,
  created_at                timestamptz NOT NULL DEFAULT NOW(),
  updated_at                timestamptz NOT NULL DEFAULT NOW(),
  created_by                text,

  event_type                text NOT NULL DEFAULT 'repair'
                              CHECK (event_type IN ('repair','replacement','maintenance','inspection','emergency','upgrade','warranty_callback')),
  title                     text NOT NULL,
  description               text,
  status                    text NOT NULL DEFAULT 'completed'
                              CHECK (status IN ('scheduled','in_progress','completed','cancelled','on_hold')),

  completed_date            date,
  scheduled_date            date,

  contractor_name           text,
  contractor_contact        text,

  cost_estimated            numeric(12,2),
  cost_actual               numeric(12,2),

  materials_used            jsonb DEFAULT '[]',
  photos                    jsonb DEFAULT '[]',
  documents                 jsonb DEFAULT '[]',

  warranty_expiration_date  date,
  warranty_notes            text,

  recurring                 boolean NOT NULL DEFAULT false,
  recurrence_interval_months integer,

  lessons_learned           text
);

CREATE INDEX IF NOT EXISTS idx_maintenance_property  ON maintenance_events (property_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_lead      ON maintenance_events (lead_id) WHERE lead_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_maintenance_completed ON maintenance_events (completed_date DESC);

-- ── 4. WARRANTY RECORDS ───────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS warranty_records (
  id                        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id bigint NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  maintenance_event_id      uuid REFERENCES maintenance_events(id) ON DELETE SET NULL,
  created_at                timestamptz NOT NULL DEFAULT NOW(),
  updated_at                timestamptz NOT NULL DEFAULT NOW(),
  created_by                text,

  item_name                 text NOT NULL,
  manufacturer              text,
  model_number              text,
  serial_number             text,
  installation_date         date,
  warranty_start_date       date,
  warranty_expiration_date  date,
  warranty_duration_months  integer,

  warranty_type             text NOT NULL DEFAULT 'contractor'
                              CHECK (warranty_type IN ('manufacturer','contractor','extended','implied','none')),

  contractor_name           text,
  contractor_contact        text,
  coverage_notes            text,

  status                    text NOT NULL DEFAULT 'active'
                              CHECK (status IN ('active','expired','claimed','void','pending')),

  documents                 jsonb DEFAULT '[]',
  alert_days_before         integer NOT NULL DEFAULT 90
);

CREATE INDEX IF NOT EXISTS idx_warranty_property ON warranty_records (property_id);
CREATE INDEX IF NOT EXISTS idx_warranty_expiry   ON warranty_records (warranty_expiration_date);
CREATE INDEX IF NOT EXISTS idx_warranty_status   ON warranty_records (status) WHERE status = 'active';

-- ── 5. DISPUTE EVENTS ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS dispute_events (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id bigint NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  lead_id               uuid REFERENCES leads(id) ON DELETE SET NULL,
  created_at            timestamptz NOT NULL DEFAULT NOW(),
  updated_at            timestamptz NOT NULL DEFAULT NOW(),
  created_by            text,

  title                 text NOT NULL,
  description           text,
  dispute_type          text NOT NULL DEFAULT 'scope'
                          CHECK (dispute_type IN ('payment','scope','warranty','damage','contractor','access','timeline','other')),
  status                text NOT NULL DEFAULT 'open'
                          CHECK (status IN ('open','resolved','escalated','legal','dismissed','mediation')),

  opened_date           date NOT NULL DEFAULT CURRENT_DATE,
  resolved_date         date,

  parties_involved      text[] DEFAULT '{}',
  amount_disputed       numeric(12,2),
  amount_resolved       numeric(12,2),

  timeline_entries      jsonb DEFAULT '[]',
  documents             jsonb DEFAULT '[]',
  resolution_notes      text,
  lessons_learned       text
);

CREATE INDEX IF NOT EXISTS idx_dispute_property ON dispute_events (property_id);
CREATE INDEX IF NOT EXISTS idx_dispute_status   ON dispute_events (status) WHERE status IN ('open','escalated','legal');

-- ── 6. INSPECTION RECORDS ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS inspection_records (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id bigint NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  created_at            timestamptz NOT NULL DEFAULT NOW(),
  updated_at            timestamptz NOT NULL DEFAULT NOW(),
  created_by            text,

  inspection_type       text NOT NULL DEFAULT 'general'
                          CHECK (inspection_type IN ('general','pre_listing','permit','insurance','code','structural','roof','pest','hvac','plumbing','electrical','environmental','other')),

  inspector_name        text,
  inspector_company     text,
  inspector_license     text,
  inspection_date       date,
  report_date           date,

  overall_condition     text
                          CHECK (overall_condition IN ('excellent','good','fair','poor','critical')),

  findings              jsonb DEFAULT '[]',
  summary               text,
  report_url            text,
  photos                jsonb DEFAULT '[]',

  follow_up_required    boolean NOT NULL DEFAULT false,
  follow_up_notes       text,
  follow_up_due_date    date
);

CREATE INDEX IF NOT EXISTS idx_inspection_property ON inspection_records (property_id);
CREATE INDEX IF NOT EXISTS idx_inspection_date     ON inspection_records (inspection_date DESC);

-- ── 7. RECURRING ISSUES ───────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS recurring_issues (
  id                          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id bigint NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  created_at                  timestamptz NOT NULL DEFAULT NOW(),
  updated_at                  timestamptz NOT NULL DEFAULT NOW(),
  created_by                  text,

  issue_title                 text NOT NULL,
  description                 text,
  issue_category              text NOT NULL
                                CHECK (issue_category IN ('plumbing','roofing','electrical','hvac','moisture','structural','pest','drainage','foundation','windows','doors','appliance','other')),
  severity                    text NOT NULL DEFAULT 'moderate'
                                CHECK (severity IN ('minor','moderate','major','critical')),
  status                      text NOT NULL DEFAULT 'active'
                                CHECK (status IN ('active','monitoring','resolved','recurring','dormant')),

  first_observed_date         date,
  last_observed_date          date,
  occurrence_count            integer NOT NULL DEFAULT 1,
  linked_maintenance_event_ids text[] DEFAULT '{}',
  estimated_root_cause        text,
  pattern_notes               text,
  recommended_action          text
);

CREATE INDEX IF NOT EXISTS idx_recurring_property ON recurring_issues (property_id);
CREATE INDEX IF NOT EXISTS idx_recurring_status   ON recurring_issues (status) WHERE status IN ('active','recurring');

-- ── 8. PROPERTY TIMELINE ENTRIES ──────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS property_timeline_entries (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id bigint NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  created_at          timestamptz NOT NULL DEFAULT NOW(),
  created_by          text,

  entry_type          text NOT NULL
                        CHECK (entry_type IN (
                          'lead','maintenance_event','warranty_record',
                          'dispute_event','inspection_record','recurring_issue','note'
                        )),
  entry_date          date NOT NULL,
  title               text NOT NULL,
  summary             text,
  linked_record_id    text,
  linked_record_type  text,
  severity            text,
  cost                numeric(12,2),
  status              text
);

CREATE INDEX IF NOT EXISTS idx_timeline_property ON property_timeline_entries (property_id, entry_date DESC);

-- ── 9. Timeline trigger: maintenance_events ───────────────────────────────────

CREATE OR REPLACE FUNCTION fn_timeline_from_maintenance()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO property_timeline_entries (
    property_id, created_by, entry_type, entry_date,
    title, summary, linked_record_id, linked_record_type, cost, status
  ) VALUES (
    NEW.property_id, NEW.created_by, 'maintenance_event',
    COALESCE(NEW.completed_date, NEW.scheduled_date, CURRENT_DATE),
    NEW.title, NEW.description, NEW.id::text, 'maintenance_events',
    NEW.cost_actual, NEW.status
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_timeline_from_maintenance ON maintenance_events;
CREATE TRIGGER trg_timeline_from_maintenance
  AFTER INSERT ON maintenance_events
  FOR EACH ROW EXECUTE FUNCTION fn_timeline_from_maintenance();

-- ── 10. Timeline trigger: dispute_events ─────────────────────────────────────

CREATE OR REPLACE FUNCTION fn_timeline_from_dispute()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO property_timeline_entries (
    property_id, created_by, entry_type, entry_date,
    title, summary, linked_record_id, linked_record_type, cost, status, severity
  ) VALUES (
    NEW.property_id, NEW.created_by, 'dispute_event', NEW.opened_date,
    NEW.title, NEW.description, NEW.id::text, 'dispute_events',
    NEW.amount_disputed, NEW.status, 'major'
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_timeline_from_dispute ON dispute_events;
CREATE TRIGGER trg_timeline_from_dispute
  AFTER INSERT ON dispute_events
  FOR EACH ROW EXECUTE FUNCTION fn_timeline_from_dispute();

-- ── 11. Timeline trigger: inspection_records ──────────────────────────────────

CREATE OR REPLACE FUNCTION fn_timeline_from_inspection()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO property_timeline_entries (
    property_id, created_by, entry_type, entry_date,
    title, summary, linked_record_id, linked_record_type, status, severity
  ) VALUES (
    NEW.property_id, NEW.created_by, 'inspection_record',
    COALESCE(NEW.inspection_date, CURRENT_DATE),
    COALESCE(NEW.inspection_type, 'general') || ' inspection',
    NEW.summary, NEW.id::text, 'inspection_records',
    NEW.overall_condition,
    CASE NEW.overall_condition
      WHEN 'poor' THEN 'major' WHEN 'critical' THEN 'critical' ELSE 'minor'
    END
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_timeline_from_inspection ON inspection_records;
CREATE TRIGGER trg_timeline_from_inspection
  AFTER INSERT ON inspection_records
  FOR EACH ROW EXECUTE FUNCTION fn_timeline_from_inspection();

-- ── 12. RPCs ─────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION get_expiring_warranties(
  days_ahead integer DEFAULT 90,
  p_property_id bigint DEFAULT NULL
)
RETURNS TABLE (
  id uuid, property_id bigint, item_name text, warranty_type text,
  warranty_expiration_date date, days_until_expiry integer,
  contractor_name text, coverage_notes text, status text,
  alert_days_before integer
)
LANGUAGE plpgsql STABLE AS $$
BEGIN
  RETURN QUERY
  SELECT w.id, w.property_id, w.item_name, w.warranty_type,
    w.warranty_expiration_date,
    (w.warranty_expiration_date - CURRENT_DATE)::integer,
    w.contractor_name, w.coverage_notes, w.status, w.alert_days_before
  FROM warranty_records w
  WHERE w.status = 'active'
    AND w.warranty_expiration_date IS NOT NULL
    AND w.warranty_expiration_date BETWEEN CURRENT_DATE AND (CURRENT_DATE + days_ahead)
    AND (p_property_id IS NULL OR w.property_id = p_property_id)
  ORDER BY w.warranty_expiration_date ASC;
END;
$$;

CREATE OR REPLACE FUNCTION get_property_summary(p_id bigint)
RETURNS TABLE (
  property_id bigint, canonical_address text,
  total_leads bigint, total_maintenance bigint,
  total_warranties bigint, active_warranties bigint,
  open_disputes bigint, pending_inspections bigint,
  active_recurring bigint, last_event_date date,
  estimated_total_spend numeric
)
LANGUAGE plpgsql STABLE AS $$
BEGIN
  RETURN QUERY
  SELECT
    p.id,
    p.canonical_address,
    (SELECT COUNT(*) FROM leads l WHERE l.property_id = p.id),
    (SELECT COUNT(*) FROM maintenance_events me WHERE me.property_id = p.id),
    (SELECT COUNT(*) FROM warranty_records wr WHERE wr.property_id = p.id),
    (SELECT COUNT(*) FROM warranty_records wr WHERE wr.property_id = p.id AND wr.status = 'active'),
    (SELECT COUNT(*) FROM dispute_events de WHERE de.property_id = p.id AND de.status IN ('open','escalated','legal')),
    (SELECT COUNT(*) FROM inspection_records ir WHERE ir.property_id = p.id AND ir.follow_up_required = true),
    (SELECT COUNT(*) FROM recurring_issues ri WHERE ri.property_id = p.id AND ri.status IN ('active','recurring')),
    (SELECT MAX(entry_date) FROM property_timeline_entries te WHERE te.property_id = p.id),
    (SELECT COALESCE(SUM(me.cost_actual), 0) FROM maintenance_events me WHERE me.property_id = p.id)
  FROM properties p
  WHERE p.id = p_id;
END;
$$;

-- ── 13. Address normalizer (SQL version for backfill) ─────────────────────────

CREATE OR REPLACE FUNCTION normalize_address_for_backfill(
  p_street text, p_city text, p_state text, p_zip text
) RETURNS text LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE v text;
BEGIN
  v := LOWER(TRIM(REGEXP_REPLACE(
    COALESCE(p_street,'') || ', ' || COALESCE(p_city,'') || ', ' ||
    COALESCE(p_state,'') || ' ' || LEFT(COALESCE(p_zip,''),5),
    '\s+', ' ', 'g'
  )));
  v := REGEXP_REPLACE(v, '\bstreet\b',    'st',   'g');
  v := REGEXP_REPLACE(v, '\bavenue\b',    'ave',  'g');
  v := REGEXP_REPLACE(v, '\bboulevard\b', 'blvd', 'g');
  v := REGEXP_REPLACE(v, '\bdrive\b',     'dr',   'g');
  v := REGEXP_REPLACE(v, '\broad\b',      'rd',   'g');
  v := REGEXP_REPLACE(v, '\bcourt\b',     'ct',   'g');
  v := REGEXP_REPLACE(v, '\blane\b',      'ln',   'g');
  v := REGEXP_REPLACE(v, '\bplace\b',     'pl',   'g');
  v := REGEXP_REPLACE(v, '\bterrace\b',   'ter',  'g');
  v := REGEXP_REPLACE(v, '\btrail\b',     'trl',  'g');
  v := REGEXP_REPLACE(v, '\bcircle\b',    'cir',  'g');
  v := REGEXP_REPLACE(v, '\bparkway\b',   'pkwy', 'g');
  v := REGEXP_REPLACE(v, '\bhighway\b',   'hwy',  'g');
  v := REGEXP_REPLACE(v, '\bnorth\b',     'n',    'g');
  v := REGEXP_REPLACE(v, '\bsouth\b',     's',    'g');
  v := REGEXP_REPLACE(v, '\beast\b',      'e',    'g');
  v := REGEXP_REPLACE(v, '\bwest\b',      'w',    'g');
  v := REGEXP_REPLACE(v, '\bnortheast\b', 'ne',   'g');
  v := REGEXP_REPLACE(v, '\bnorthwest\b', 'nw',   'g');
  v := REGEXP_REPLACE(v, '\bsoutheast\b', 'se',   'g');
  v := REGEXP_REPLACE(v, '\bsouthwest\b', 'sw',   'g');
  v := REGEXP_REPLACE(v, '\bapartment\b', 'apt',  'g');
  v := REGEXP_REPLACE(v, '\bsuite\b',     'ste',  'g');
  RETURN TRIM(v);
END;
$$;

-- ── 14. BACKFILL: leads → properties ─────────────────────────────────────────

DO $$
DECLARE
  r RECORD;
  v_canonical text;
  v_prop_id   bigint;
  v_state     char(2);
BEGIN
  FOR r IN
    SELECT id, address, city, state, zip, property_facts
    FROM leads
    WHERE property_id IS NULL
      AND COALESCE(TRIM(address), '') <> ''
  LOOP
    v_state := UPPER(LEFT(TRIM(COALESCE(r.state, 'XX')), 2));
    v_canonical := normalize_address_for_backfill(r.address, r.city, v_state, r.zip);

    SELECT id INTO v_prop_id
    FROM properties
    WHERE canonical_address = v_canonical
    LIMIT 1;

    IF v_prop_id IS NULL THEN
      INSERT INTO properties (
        canonical_address, street_line_1, city, state, zip,
        property_type, year_built, square_feet,
        bedrooms, bathrooms, lot_size, parcel_number,
        match_confidence, needs_review
      ) VALUES (
        v_canonical,
        COALESCE(r.address, ''),
        COALESCE(r.city, ''),
        v_state,
        LEFT(COALESCE(r.zip, ''), 5),
        r.property_facts->>'propertyType',
        r.property_facts->>'yearBuilt',
        r.property_facts->>'squareFeet',
        r.property_facts->>'bedrooms',
        r.property_facts->>'bathrooms',
        r.property_facts->>'lotSize',
        r.property_facts->>'parcelNumber',
        'high', false
      )
      RETURNING id INTO v_prop_id;
    END IF;

    UPDATE leads SET property_id = v_prop_id WHERE id = r.id;
  END LOOP;
END;
$$;

-- Flag same ZIP + street number duplicates
DO $$
DECLARE r RECORD;
BEGIN
  FOR r IN
    SELECT p.zip,
      SPLIT_PART(p.canonical_address, ' ', 1) AS street_num,
      ARRAY_AGG(p.id) AS prop_ids
    FROM properties p
    GROUP BY p.zip, SPLIT_PART(p.canonical_address, ' ', 1)
    HAVING COUNT(*) > 1
      AND SPLIT_PART(MAX(p.canonical_address), ' ', 1) ~ '^\d'
  LOOP
    UPDATE properties
    SET needs_review = true,
        review_reason = 'Multiple property records share this ZIP + street number. Possible duplicate — review and merge if appropriate.'
    WHERE id = ANY(r.prop_ids);
  END LOOP;
END;
$$;

-- ── 15. updated_at trigger ────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION fn_set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$;

DO $$
DECLARE tbl text;
BEGIN
  FOREACH tbl IN ARRAY ARRAY[
    'properties','maintenance_events','warranty_records',
    'dispute_events','inspection_records','recurring_issues'
  ] LOOP
    EXECUTE FORMAT(
      'DROP TRIGGER IF EXISTS trg_updated_at ON %I;
       CREATE TRIGGER trg_updated_at
         BEFORE UPDATE ON %I
         FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();',
      tbl, tbl
    );
  END LOOP;
END;
$$;

COMMIT;



-- ============================================================================
-- Source: Caude may 17th/5.18.2026/003_material_agent_fixed.sql
-- ============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- Shelter Prep — Material agent migration (CORRECTED)
-- 003_material_agent_fixed.sql
-- Uses lead_id (references leads table), not work_request_id
-- Run after 002_property_foundation_fixed.sql
-- ─────────────────────────────────────────────────────────────────────────────

BEGIN;

-- ── 1. Extend pricing_memory_entries ─────────────────────────────────────────

ALTER TABLE pricing_memory_entries
  ADD COLUMN IF NOT EXISTS supplier_name                text,
  ADD COLUMN IF NOT EXISTS supplier_sku                 text,
  ADD COLUMN IF NOT EXISTS supplier_product_url         text,
  ADD COLUMN IF NOT EXISTS package_size                 numeric,
  ADD COLUMN IF NOT EXISTS package_unit                 text,
  ADD COLUMN IF NOT EXISTS waste_factor                 numeric NOT NULL DEFAULT 1.0,
  ADD COLUMN IF NOT EXISTS procurement_lead_time_days   integer,
  ADD COLUMN IF NOT EXISTS trade                        text,
  ADD COLUMN IF NOT EXISTS work_type                    text,
  ADD COLUMN IF NOT EXISTS times_approved               integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_approved_at             timestamptz,
  ADD COLUMN IF NOT EXISTS last_approved_price          numeric;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'pricing_memory_entries'
      AND column_name = 'work_type'
  ) THEN
    RAISE EXCEPTION 'Required column public.pricing_memory_entries.work_type is missing before material-agent indexes/functions run';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'pricing_memory_entries'
      AND column_name = 'zip'
  ) THEN
    RAISE EXCEPTION 'Required column public.pricing_memory_entries.zip is missing before material-agent indexes/functions run';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'pricing_memory_entries'
      AND column_name = 'human_verified'
  ) THEN
    RAISE EXCEPTION 'Required column public.pricing_memory_entries.human_verified is missing before material-agent indexes/functions run';
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_pme_supplier    ON pricing_memory_entries (supplier_name) WHERE supplier_name IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pme_zip_work    ON pricing_memory_entries (zip, work_type) WHERE human_verified = true;

-- ── 2. material_draft_lists ───────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS material_draft_lists (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at       timestamptz NOT NULL DEFAULT NOW(),
  updated_at       timestamptz NOT NULL DEFAULT NOW(),
  created_by       text,

  lead_id          uuid REFERENCES leads(id) ON DELETE CASCADE,   -- corrected
  property_id bigint REFERENCES properties(id) ON DELETE SET NULL,

  work_type        text NOT NULL,
  zip              text NOT NULL DEFAULT '',
  description_snapshot text,

  phase            text NOT NULL DEFAULT 'rough_takeoff'
                     CHECK (phase IN ('rough_takeoff','detailed_spec')),
  status           text NOT NULL DEFAULT 'draft'
                     CHECK (status IN (
                       'draft','rough_pending_review','rough_approved',
                       'detailed_pending_review','approved','po_generated','archived'
                     )),

  rough_generated_at     timestamptz,
  rough_reviewed_at      timestamptz,
  rough_reviewed_by      text,
  rough_gc_notes         text,

  detailed_generated_at  timestamptz,
  detailed_reviewed_at   timestamptz,
  detailed_reviewed_by   text,
  detailed_gc_notes      text,

  po_id            uuid,
  ai_model         text,
  memory_context_used boolean NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_mdl_lead     ON material_draft_lists (lead_id);
CREATE INDEX IF NOT EXISTS idx_mdl_property ON material_draft_lists (property_id) WHERE property_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_mdl_status   ON material_draft_lists (status);

-- ── 3. material_draft_items ───────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS material_draft_items (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  list_id         uuid NOT NULL REFERENCES material_draft_lists(id) ON DELETE CASCADE,
  created_at      timestamptz NOT NULL DEFAULT NOW(),
  updated_at      timestamptz NOT NULL DEFAULT NOW(),

  phase           text NOT NULL DEFAULT 'rough_takeoff'
                    CHECK (phase IN ('rough_takeoff','detailed_spec')),
  category        text NOT NULL DEFAULT 'General',
  item_name       text NOT NULL,

  rough_quantity            numeric,
  rough_unit                text,
  rough_unit_price_estimate numeric,
  rough_extended_estimate   numeric,
  rough_confidence          text NOT NULL DEFAULT 'medium'
                              CHECK (rough_confidence IN ('high','medium','low')),
  rough_notes               text,

  full_description          text,
  quantity                  numeric,
  unit                      text,
  unit_price                numeric,
  waste_factor              numeric NOT NULL DEFAULT 1.0,
  package_size              numeric,
  package_unit              text,
  packages_needed           integer,
  extended_price            numeric,

  supplier_name             text,
  supplier_sku              text,
  supplier_product_url      text,
  supplier_search_url       text,

  procurement_lead_time_days integer,
  trade                     text,
  install_sequence          integer,
  trade_dependency          text,
  ai_notes                  text,

  memory_match_price        numeric,
  memory_match_supplier     text,
  memory_match_sku          text,
  memory_match_id           text,

  gc_status       text NOT NULL DEFAULT 'pending'
                    CHECK (gc_status IN ('pending','approved','edited','rejected','skipped')),
  gc_notes        text,
  gc_reviewed_at  timestamptz,
  gc_reviewed_by  text,

  final_quantity  numeric,
  final_unit_price numeric,
  final_supplier  text,
  final_sku       text,
  final_url       text,
  final_extended  numeric,

  memory_saved    boolean NOT NULL DEFAULT false,
  memory_entry_id text
);

CREATE INDEX IF NOT EXISTS idx_mdi_list      ON material_draft_items (list_id);
CREATE INDEX IF NOT EXISTS idx_mdi_gc_status ON material_draft_items (list_id, gc_status);
CREATE INDEX IF NOT EXISTS idx_mdi_sequence  ON material_draft_items (list_id, install_sequence);

-- ── 4. material_purchase_orders ───────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS material_purchase_orders (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at       timestamptz NOT NULL DEFAULT NOW(),
  updated_at       timestamptz NOT NULL DEFAULT NOW(),
  created_by       text,

  list_id          uuid NOT NULL REFERENCES material_draft_lists(id) ON DELETE CASCADE,
  lead_id          uuid REFERENCES leads(id) ON DELETE SET NULL,       -- corrected
  property_id bigint REFERENCES properties(id) ON DELETE SET NULL,

  po_number        text NOT NULL DEFAULT '',
  status           text NOT NULL DEFAULT 'draft'
                     CHECK (status IN ('draft','ready','submitted','ordered','partially_received','received','cancelled')),

  delivery_address        text,
  requested_delivery_date date,
  delivery_notes          text,

  subtotal         numeric(12,2) NOT NULL DEFAULT 0,
  tax_estimate     numeric(12,2),
  total_estimate   numeric(12,2) NOT NULL DEFAULT 0,

  gc_notes         text,
  approved_by      text,
  approved_at      timestamptz,
  primary_supplier text
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_mdl_po'
      AND conrelid = 'public.material_draft_lists'::regclass
  ) THEN
    ALTER TABLE material_draft_lists
      ADD CONSTRAINT fk_mdl_po FOREIGN KEY (po_id)
      REFERENCES material_purchase_orders(id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_mpo_list    ON material_purchase_orders (list_id);
CREATE INDEX IF NOT EXISTS idx_mpo_lead    ON material_purchase_orders (lead_id) WHERE lead_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_mpo_status  ON material_purchase_orders (status);

-- ── 5. material_purchase_order_items ─────────────────────────────────────────

CREATE TABLE IF NOT EXISTS material_purchase_order_items (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  po_id           uuid NOT NULL REFERENCES material_purchase_orders(id) ON DELETE CASCADE,
  draft_item_id   uuid REFERENCES material_draft_items(id) ON DELETE SET NULL,

  line_number     integer NOT NULL,
  supplier_name   text NOT NULL,
  item_name       text NOT NULL,
  full_description text,
  sku             text,
  product_url     text,
  quantity        numeric NOT NULL,
  unit            text NOT NULL,
  unit_price      numeric NOT NULL,
  extended_price  numeric NOT NULL,
  trade           text,
  install_sequence integer,
  notes           text
);

CREATE INDEX IF NOT EXISTS idx_mpoi_po ON material_purchase_order_items (po_id);

-- ── 6. PO number sequence ─────────────────────────────────────────────────────

CREATE SEQUENCE IF NOT EXISTS material_po_number_seq START 1000;

CREATE OR REPLACE FUNCTION next_po_number()
RETURNS text LANGUAGE plpgsql AS $$
BEGIN
  RETURN 'SP-' || TO_CHAR(NOW(), 'YYYY') || '-' || LPAD(nextval('material_po_number_seq')::text, 4, '0');
END;
$$;

-- ── 7. updated_at triggers ────────────────────────────────────────────────────

DO $$
DECLARE tbl text;
BEGIN
  FOREACH tbl IN ARRAY ARRAY['material_draft_lists','material_draft_items','material_purchase_orders'] LOOP
    EXECUTE FORMAT(
      'DROP TRIGGER IF EXISTS trg_updated_at ON %I;
       CREATE TRIGGER trg_updated_at BEFORE UPDATE ON %I
         FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();',
      tbl, tbl
    );
  END LOOP;
END;
$$;

-- ── 8. Pricing memory review RPC ──────────────────────────────────────────────

CREATE OR REPLACE FUNCTION get_pricing_memory_for_review(
  p_item_names text[],
  p_zip        text DEFAULT NULL,
  p_work_type  text DEFAULT NULL
)
RETURNS TABLE (
  item_name            text,
  verified_price       numeric,
  unit                 text,
  supplier_name        text,
  supplier_sku         text,
  supplier_product_url text,
  waste_factor         numeric,
  zip                  text,
  work_type            text,
  times_approved       integer,
  last_approved_at     timestamptz,
  source               text,
  id                   text
)
LANGUAGE plpgsql STABLE AS $$
BEGIN
  RETURN QUERY
  SELECT
    p.item_name::text, COALESCE(p.verified_price, p.unit_cost)::numeric,
    p.unit::text, p.supplier_name::text, p.supplier_sku::text,
    p.supplier_product_url::text, p.waste_factor,
    p.zip::text, p.work_type::text,
    p.times_approved, p.last_approved_at,
    p.source::text, p.id::text
  FROM pricing_memory_entries p
  WHERE
    p.human_verified = true
    AND EXISTS (
      SELECT 1 FROM unnest(p_item_names) qn
      WHERE LOWER(p.item_name) ILIKE '%' || LOWER(SPLIT_PART(qn, ' ', 1)) || '%'
         OR LOWER(p.item_name) ILIKE '%' || LOWER(SPLIT_PART(qn, ' ', 2)) || '%'
    )
    AND (p_zip IS NULL OR p.zip IS NULL OR LEFT(p.zip,3) = LEFT(p_zip,3))
    AND (p_work_type IS NULL OR p.work_type IS NULL OR LOWER(p.work_type) ILIKE '%' || LOWER(p_work_type) || '%')
  ORDER BY p.times_approved DESC, p.last_approved_at DESC NULLS LAST
  LIMIT 60;
END;
$$;

-- ── 9. Trigger: increment times_approved when GC approves ────────────────────

CREATE OR REPLACE FUNCTION fn_increment_memory_approval()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.memory_entry_id IS NOT NULL AND NEW.memory_saved = true
     AND (OLD.memory_saved = false OR OLD.memory_saved IS NULL)
  THEN
    UPDATE pricing_memory_entries
    SET
      times_approved   = COALESCE(times_approved, 0) + 1,
      last_approved_at = NOW(),
      last_approved_price = COALESCE(NEW.final_unit_price, NEW.unit_price)
    WHERE id::text = NEW.memory_entry_id;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_increment_memory_approval ON material_draft_items;
CREATE TRIGGER trg_increment_memory_approval
  AFTER UPDATE OF memory_saved ON material_draft_items
  FOR EACH ROW EXECUTE FUNCTION fn_increment_memory_approval();

COMMIT;



-- ============================================================================
-- Source: shelterprep-full-correct-20260509122305/supabase/manual_sql/run_dependable_request_foundation.sql
-- ============================================================================

-- Dependable request foundation
-- Keeps the existing leads-based app, while making every lead attach to a durable property
-- and every uploaded file retain enough Supabase Storage metadata for admin open/download.

alter table public.leads
  add column if not exists property_id bigint;

alter table public.files
  add column if not exists storage_bucket text not null default 'job-files',
  add column if not exists storage_path text,
  add column if not exists file_type text,
  add column if not exists mime_type text,
  add column if not exists file_size numeric;

update public.files
set storage_bucket = 'job-files'
where storage_bucket is null or storage_bucket = '';

update public.files
set storage_path = split_part(file_url, '/storage/v1/object/public/job-files/', 2)
where storage_path is null
  and file_url like '%/storage/v1/object/public/job-files/%';

update public.files
set file_type = case
  when lower(coalesce(mime_type, '')) like 'image/%' then 'photo'
  when lower(coalesce(storage_path, file_url, file_name, '')) like '%/photos/%' then 'photo'
  when lower(coalesce(storage_path, file_url, file_name, '')) ~ '\.(jpg|jpeg|png|gif|webp|heic|heif)$' then 'photo'
  else 'document'
end
where file_type is null or file_type = '';

create index if not exists leads_property_id_idx on public.leads(property_id);
create index if not exists files_lead_id_idx on public.files(lead_id);
create index if not exists files_storage_bucket_idx on public.files(storage_bucket);

insert into storage.buckets (id, name, public)
values ('job-files', 'job-files', false)
on conflict (id) do update set public = excluded.public;

drop policy if exists "job files anon upload" on storage.objects;
create policy "job files anon upload"
on storage.objects
for insert
to anon, authenticated
with check (bucket_id = 'job-files');

drop policy if exists "job files authenticated read" on storage.objects;
create policy "job files authenticated read"
on storage.objects
for select
to authenticated
using (bucket_id = 'job-files');

drop policy if exists "job files anon read public urls" on storage.objects;
create policy "job files anon read public urls"
on storage.objects
for select
to anon
using (bucket_id = 'job-files');

create or replace function public.normalize_property_key(
  p_address text,
  p_city text default '',
  p_state text default '',
  p_zip text default ''
)
returns text
language sql
immutable
as $$
  select lower(regexp_replace(trim(
    concat_ws(' ',
      nullif(p_address, ''),
      nullif(p_city, ''),
      nullif(p_state, ''),
      nullif(left(coalesce(p_zip, ''), 5), '')
    )
  ), '\s+', ' ', 'g'));
$$;

create or replace function public.upsert_property_for_lead(
  p_lead_id uuid,
  p_address text,
  p_city text default '',
  p_state text default '',
  p_zip text default ''
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_property_id bigint;
  v_key text;
  v_address text;
  v_city text;
  v_state text;
  v_zip text;
BEGIN
  v_address := trim(coalesce(p_address, ''));
  v_city := trim(coalesce(p_city, ''));
  v_state := upper(left(trim(coalesce(p_state, '')), 2));
  v_zip := left(regexp_replace(coalesce(p_zip, ''), '[^0-9]', '', 'g'), 5);
  v_key := public.normalize_property_key(v_address, v_city, v_state, v_zip);

  if v_address = '' then
    return null;
  end if;

  select id
  into v_property_id
  from public.properties
  where public.normalize_property_key(address, city, state, zip) = v_key
  order by id
  limit 1;

  if v_property_id is null then
    insert into public.properties (
      address,
      canonical_address,
      street_line_1,
      city,
      state,
      zip
    )
    values (
      v_address,
      v_key,
      v_address,
      v_city,
      v_state,
      v_zip
    )
    returning id into v_property_id;
  end if;

  update public.leads
  set property_id = v_property_id
  where id = p_lead_id;

  return v_property_id;
end;
$$;

grant execute on function public.upsert_property_for_lead(uuid, text, text, text, text) to anon, authenticated;

DO $$
declare
  r record;
BEGIN
  for r in
    select id, address, city, state, zip
    from public.leads
    where property_id is null
      and coalesce(trim(address), '') <> ''
  loop
    perform public.upsert_property_for_lead(r.id, r.address, r.city, r.state, r.zip);
  end loop;
END $$;



-- ============================================================================
-- Source: shelterprep-full-correct-20260509122305/supabase/manual_sql/run_site_media_intelligence.sql
-- ============================================================================

-- Site Media Intelligence
-- Uses existing uploaded files first. No outside media scraping or autonomous approval.

create table if not exists public.property_media_analysis (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  property_id bigint,
  lead_id uuid references public.leads(id) on delete cascade,
  source_type text not null default 'uploaded_photo'
    check (source_type in ('uploaded_photo', 'inspection_photo', 'listing_photo', 'satellite', 'map', 'aerial', 'street_view', 'other')),
  source_url text,
  source_file_id uuid,
  captured_at timestamptz,
  analyzed_at timestamptz not null default now(),
  roof_size_estimate text,
  roof_pitch_estimate text,
  roof_complexity_notes text,
  ladder_access_notes text,
  lift_access_notes text,
  crane_access_notes text,
  truck_access_notes text,
  machinery_access_notes text,
  staging_notes text,
  slope_notes text,
  water_ravine_notes text,
  tree_obstruction_notes text,
  overhead_obstruction_notes text,
  terrain_risk_level text not null default 'unknown'
    check (terrain_risk_level in ('low', 'medium', 'high', 'unknown')),
  access_risk_level text not null default 'unknown'
    check (access_risk_level in ('low', 'medium', 'high', 'unknown')),
  estimate_impact_notes text,
  missing_info text,
  confidence text not null default 'low'
    check (confidence in ('low', 'medium', 'high')),
  review_status text not null default 'ai_draft'
    check (review_status in ('ai_draft', 'needs_review', 'human_reviewed', 'human_verified', 'rejected')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  admin_notes text
);

create table if not exists public.property_media_findings (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  property_media_analysis_id uuid references public.property_media_analysis(id) on delete cascade,
  property_id bigint,
  lead_id uuid references public.leads(id) on delete cascade,
  finding_type text not null default 'access',
  observation text not null default '',
  field_consequence text not null default '',
  estimate_impact text not null default '',
  access_notes text not null default '',
  safety_notes text not null default '',
  confidence text not null default 'low'
    check (confidence in ('low', 'medium', 'high')),
  source_file_id uuid,
  review_status text not null default 'needs_review'
    check (review_status in ('ai_draft', 'needs_review', 'approved', 'rejected', 'human_verified')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  admin_notes text not null default ''
);

DO $$
BEGIN
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'property_media_analysis'
      and column_name = 'property_id'
      and data_type = 'uuid'
  ) then
    alter table public.property_media_analysis
      alter column property_id type bigint using null;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'property_media_findings'
      and column_name = 'property_id'
      and data_type = 'uuid'
  ) then
    alter table public.property_media_findings
      alter column property_id type bigint using null;
  end if;

  if to_regclass('public.properties') is not null then
    if not exists (select 1 from pg_constraint where conname = 'property_media_analysis_property_id_fkey') then
      alter table public.property_media_analysis
        add constraint property_media_analysis_property_id_fkey
        foreign key (property_id) references public.properties(id) on delete set null;
    end if;

    if not exists (select 1 from pg_constraint where conname = 'property_media_findings_property_id_fkey') then
      alter table public.property_media_findings
        add constraint property_media_findings_property_id_fkey
        foreign key (property_id) references public.properties(id) on delete set null;
    end if;
  end if;

  if to_regclass('public.files') is not null then
    if not exists (select 1 from pg_constraint where conname = 'property_media_analysis_source_file_id_fkey') then
      alter table public.property_media_analysis
        add constraint property_media_analysis_source_file_id_fkey
        foreign key (source_file_id) references public.files(id) on delete set null;
    end if;

    if not exists (select 1 from pg_constraint where conname = 'property_media_findings_source_file_id_fkey') then
      alter table public.property_media_findings
        add constraint property_media_findings_source_file_id_fkey
        foreign key (source_file_id) references public.files(id) on delete set null;
    end if;
  end if;
END $$;

create index if not exists property_media_analysis_lead_idx on public.property_media_analysis(lead_id);
create index if not exists property_media_analysis_property_idx on public.property_media_analysis(property_id);
create index if not exists property_media_analysis_source_file_idx on public.property_media_analysis(source_file_id);
create index if not exists property_media_analysis_review_idx on public.property_media_analysis(review_status);

create index if not exists property_media_findings_analysis_idx on public.property_media_findings(property_media_analysis_id);
create index if not exists property_media_findings_lead_idx on public.property_media_findings(lead_id);
create index if not exists property_media_findings_property_idx on public.property_media_findings(property_id);
create index if not exists property_media_findings_source_file_idx on public.property_media_findings(source_file_id);
create index if not exists property_media_findings_review_idx on public.property_media_findings(review_status);

create or replace function public.touch_property_media_updated_at()
returns trigger
language plpgsql
as $$
BEGIN
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists touch_property_media_analysis_updated_at on public.property_media_analysis;
create trigger touch_property_media_analysis_updated_at
before update on public.property_media_analysis
for each row execute function public.touch_property_media_updated_at();

drop trigger if exists touch_property_media_findings_updated_at on public.property_media_findings;
create trigger touch_property_media_findings_updated_at
before update on public.property_media_findings
for each row execute function public.touch_property_media_updated_at();

alter table public.property_media_analysis enable row level security;
alter table public.property_media_findings enable row level security;

drop policy if exists "property media analysis admin manage" on public.property_media_analysis;
create policy "property media analysis admin manage"
on public.property_media_analysis
for all
to authenticated
using (public.is_admin_or_owner())
with check (public.is_admin_or_owner());

drop policy if exists "property media analysis estimator read" on public.property_media_analysis;
create policy "property media analysis estimator read"
on public.property_media_analysis
for select
to authenticated
using (public.current_user_role() in ('admin', 'owner', 'estimator'));

drop policy if exists "property media analysis estimator create drafts" on public.property_media_analysis;
create policy "property media analysis estimator create drafts"
on public.property_media_analysis
for insert
to authenticated
with check (
  public.current_user_role() = 'estimator'
  and review_status in ('ai_draft', 'needs_review')
);

drop policy if exists "property media findings admin manage" on public.property_media_findings;
create policy "property media findings admin manage"
on public.property_media_findings
for all
to authenticated
using (public.is_admin_or_owner())
with check (public.is_admin_or_owner());

drop policy if exists "property media findings estimator read" on public.property_media_findings;
create policy "property media findings estimator read"
on public.property_media_findings
for select
to authenticated
using (public.current_user_role() in ('admin', 'owner', 'estimator'));

drop policy if exists "property media findings estimator create drafts" on public.property_media_findings;
create policy "property media findings estimator create drafts"
on public.property_media_findings
for insert
to authenticated
with check (
  public.current_user_role() = 'estimator'
  and review_status in ('ai_draft', 'needs_review')
);



-- ============================================================================
-- Source: shelterprep-full-correct-20260509122305/supabase/migrations/202605200001_curated_labor_cost_memory.sql
-- ============================================================================

-- Curated Labor Cost Memory
-- Extends labor_rates so draft labor ranges can become human-verified labor memory.

create table if not exists public.labor_rates (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  trade text not null,
  job_type text,
  unit text not null default 'hour',
  low_rate numeric,
  typical_rate numeric,
  high_rate numeric,
  minimum_charge numeric not null default 0,
  trip_charge numeric not null default 0,
  disposal_fee numeric not null default 0,
  zip text,
  region text,
  source text,
  confidence text not null default 'labor_review',
  human_verified boolean not null default false,
  last_checked timestamptz,
  notes text
);

alter table public.labor_rates
  add column if not exists labor_hours_low numeric,
  add column if not exists labor_hours_high numeric,
  add column if not exists hourly_rate_low numeric,
  add column if not exists hourly_rate_high numeric,
  add column if not exists access_multiplier numeric not null default 1,
  add column if not exists setup_cleanup_hours numeric not null default 0,
  add column if not exists source_links jsonb not null default '[]'::jsonb,
  add column if not exists source_priority text,
  add column if not exists admin_override_note text,
  add column if not exists admin_edited boolean not null default false,
  add column if not exists verified_at timestamptz,
  add column if not exists verified_by uuid references auth.users(id) on delete set null;

create index if not exists labor_rates_verified_priority_idx
  on public.labor_rates(human_verified, source_priority, updated_at desc);

create index if not exists labor_rates_trade_job_idx
  on public.labor_rates(trade, job_type);

alter table public.labor_rates enable row level security;

drop policy if exists "labor rates admin owner manage" on public.labor_rates;
create policy "labor rates admin owner manage"
on public.labor_rates
for all
to authenticated
using (public.current_user_role() in ('admin', 'owner'))
with check (public.current_user_role() in ('admin', 'owner'));

drop policy if exists "labor rates estimator read" on public.labor_rates;
create policy "labor rates estimator read"
on public.labor_rates
for select
to authenticated
using (public.current_user_role() in ('admin', 'owner', 'estimator'));



-- ============================================================================
-- Source: shelterprep-full-correct-20260509122305/supabase/migrations/202605200002_material_complexity_classification.sql
-- ============================================================================

-- Material List Complexity Classification
-- Adds review metadata for generated material rows.

alter table public.estimate_items
  add column if not exists material_complexity text
    check (material_complexity in ('small_simple', 'medium_defined', 'large_complex', 'unknown_needs_review')),
  add column if not exists quantity_low numeric,
  add column if not exists quantity_high numeric,
  add column if not exists required_optional text not null default 'required'
    check (required_optional in ('required', 'optional', 'review')),
  add column if not exists admin_editable boolean not null default true,
  add column if not exists material_review_notes text;

create index if not exists estimate_items_material_complexity_idx
  on public.estimate_items(material_complexity);



-- ============================================================================
-- Source: shelterprep-full-correct-20260509122305/supabase/migrations/202605150001_source_lessons_field_agent.sql
-- ============================================================================

-- Field Lesson Agent source lesson drafts.
-- Real life is the source of intelligence; AI drafts structure; humans verify meaning.
-- Source lessons do not become operational memory until an admin/owner approves them.

create table if not exists public.source_lessons (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  created_by uuid,
  source_type text not null default 'field_note',
  source_url text not null default '',
  source_title text not null default '',
  work_type text not null default '',
  problem_description text not null default '',
  admin_intent text not null default '',
  lesson_summary text not null default '',
  observed_method text not null default '',
  hidden_labor text not null default '',
  job_steps jsonb not null default '[]'::jsonb,
  tools_materials jsonb not null default '[]'::jsonb,
  safety_notes text not null default '',
  access_notes text not null default '',
  cleanup_notes text not null default '',
  estimate_impact text not null default '',
  missing_info_questions jsonb not null default '[]'::jsonb,
  applies_when text not null default '',
  does_not_apply_when text not null default '',
  confidence text not null default 'low',
  status text not null default 'draft',
  approved_by uuid,
  approved_at timestamptz,
  admin_notes text not null default '',
  linked_property_id text,
  linked_work_request_id text,
  linked_repair_item_id text
);

alter table public.source_lessons
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists created_by uuid,
  add column if not exists source_type text not null default 'field_note',
  add column if not exists source_url text not null default '',
  add column if not exists source_title text not null default '',
  add column if not exists work_type text not null default '',
  add column if not exists problem_description text not null default '',
  add column if not exists admin_intent text not null default '',
  add column if not exists lesson_summary text not null default '',
  add column if not exists observed_method text not null default '',
  add column if not exists hidden_labor text not null default '',
  add column if not exists job_steps jsonb not null default '[]'::jsonb,
  add column if not exists tools_materials jsonb not null default '[]'::jsonb,
  add column if not exists safety_notes text not null default '',
  add column if not exists access_notes text not null default '',
  add column if not exists cleanup_notes text not null default '',
  add column if not exists estimate_impact text not null default '',
  add column if not exists missing_info_questions jsonb not null default '[]'::jsonb,
  add column if not exists applies_when text not null default '',
  add column if not exists does_not_apply_when text not null default '',
  add column if not exists confidence text not null default 'low',
  add column if not exists status text not null default 'draft',
  add column if not exists approved_by uuid,
  add column if not exists approved_at timestamptz,
  add column if not exists admin_notes text not null default '',
  add column if not exists linked_property_id text,
  add column if not exists linked_work_request_id text,
  add column if not exists linked_repair_item_id text;

DO $$
BEGIN
  if not exists (
    select 1 from pg_constraint where conname = 'source_lessons_source_type_check'
  ) then
    alter table public.source_lessons
      add constraint source_lessons_source_type_check
      check (source_type in ('youtube', 'article', 'manual', 'field_note'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'source_lessons_confidence_check'
  ) then
    alter table public.source_lessons
      add constraint source_lessons_confidence_check
      check (confidence in ('low', 'medium', 'high'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'source_lessons_status_check'
  ) then
    alter table public.source_lessons
      add constraint source_lessons_status_check
      check (status in ('draft', 'needs_review', 'approved', 'rejected', 'archived'));
  end if;
END $$;

create index if not exists source_lessons_created_at_idx on public.source_lessons(created_at desc);
create index if not exists source_lessons_status_idx on public.source_lessons(status);
create index if not exists source_lessons_source_type_idx on public.source_lessons(source_type);
create index if not exists source_lessons_work_type_idx on public.source_lessons(work_type);
create index if not exists source_lessons_linked_property_idx on public.source_lessons(linked_property_id);
create index if not exists source_lessons_linked_request_idx on public.source_lessons(linked_work_request_id);

alter table public.source_lessons enable row level security;

drop policy if exists "source lessons read" on public.source_lessons;
create policy "source lessons read"
on public.source_lessons
for select
to authenticated
using (public.current_user_role() in ('admin', 'owner', 'estimator'));

drop policy if exists "source lessons draft insert" on public.source_lessons;
create policy "source lessons draft insert"
on public.source_lessons
for insert
to authenticated
with check (
  public.current_user_role() in ('admin', 'owner', 'estimator')
  and created_by = auth.uid()
  and status in ('draft', 'needs_review')
  and approved_by is null
  and approved_at is null
);

drop policy if exists "source lessons admin update" on public.source_lessons;
create policy "source lessons admin update"
on public.source_lessons
for update
to authenticated
using (public.is_admin_or_owner())
with check (public.is_admin_or_owner());

drop policy if exists "source lessons estimator edit draft" on public.source_lessons;
create policy "source lessons estimator edit draft"
on public.source_lessons
for update
to authenticated
using (
  public.current_user_role() = 'estimator'
  and status in ('draft', 'needs_review')
  and approved_by is null
  and approved_at is null
)
with check (
  public.current_user_role() = 'estimator'
  and status in ('draft', 'needs_review')
  and approved_by is null
  and approved_at is null
);


-- ============================================================================
-- Source: shelterprep-full-correct-20260509122305/supabase/migrations/202605200003_curated_lesson_comprehension_grade.sql
-- ============================================================================

-- Curated Lesson Intake comprehension grading.
-- Lesson drafts remain non-memory until admin comprehension grade and review rules allow promotion.

alter table public.source_lessons
  add column if not exists source_links jsonb not null default '[]'::jsonb,
  add column if not exists operational_meaning text not null default '',
  add column if not exists materials_tools_equipment jsonb not null default '[]'::jsonb,
  add column if not exists cleanup_disposal text not null default '',
  add column if not exists comprehension_grade text,
  add column if not exists admin_feedback text not null default '',
  add column if not exists human_review_status text not null default 'needs_review',
  add column if not exists memory_destination text not null default 'none',
  add column if not exists original_draft jsonb,
  add column if not exists edited_lesson jsonb,
  add column if not exists reviewed_by uuid references auth.users(id) on delete set null,
  add column if not exists reviewed_at timestamptz;

DO $$
BEGIN
  if not exists (
    select 1 from pg_constraint where conname = 'source_lessons_comprehension_grade_check'
  ) then
    alter table public.source_lessons
      add constraint source_lessons_comprehension_grade_check
      check (comprehension_grade is null or comprehension_grade in ('A', 'B', 'C', 'D', 'F'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'source_lessons_human_review_status_check'
  ) then
    alter table public.source_lessons
      add constraint source_lessons_human_review_status_check
      check (human_review_status in ('ai_draft', 'needs_review', 'edited', 'approved', 'rejected', 'human_verified'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'source_lessons_memory_destination_check'
  ) then
    alter table public.source_lessons
      add constraint source_lessons_memory_destination_check
      check (memory_destination in ('none', 'project_specific', 'global_operational', 'material_pricing', 'contractor_scope', 'job_execution_context'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'source_lessons_source_links_is_array_check'
  ) then
    alter table public.source_lessons
      add constraint source_lessons_source_links_is_array_check
      check (jsonb_typeof(source_links) = 'array');
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'source_lessons_materials_tools_equipment_is_array_check'
  ) then
    alter table public.source_lessons
      add constraint source_lessons_materials_tools_equipment_is_array_check
      check (jsonb_typeof(materials_tools_equipment) = 'array');
  end if;
END $$;

update public.source_lessons
set source_links = jsonb_build_array(
  jsonb_build_object(
    'url', source_url,
    'title', source_title,
    'source_type', source_type,
    'date_checked', created_at
  )
)
where source_url <> ''
  and source_links = '[]'::jsonb;

update public.source_lessons
set
  operational_meaning = observed_method
where operational_meaning = ''
  and observed_method <> '';

update public.source_lessons
set
  materials_tools_equipment = tools_materials
where materials_tools_equipment = '[]'::jsonb
  and jsonb_typeof(tools_materials) = 'array'
  and tools_materials <> '[]'::jsonb;

update public.source_lessons
set
  cleanup_disposal = cleanup_notes
where cleanup_disposal = ''
  and cleanup_notes <> '';

update public.source_lessons
set
  human_review_status = case
    when status = 'approved' then 'human_verified'
    when status = 'rejected' then 'rejected'
    when status in ('draft', 'needs_review') then 'needs_review'
    else human_review_status
  end
where human_review_status in ('', 'needs_review');

create index if not exists source_lessons_comprehension_grade_idx on public.source_lessons(comprehension_grade);
create index if not exists source_lessons_human_review_status_idx on public.source_lessons(human_review_status);
create index if not exists source_lessons_memory_destination_idx on public.source_lessons(memory_destination);

create or replace view public.curated_lessons as
select
  id,
  source_links,
  admin_intent,
  work_type as trade_category,
  lesson_summary,
  operational_meaning,
  estimate_impact,
  hidden_labor,
  materials_tools_equipment,
  cleanup_disposal,
  confidence,
  comprehension_grade,
  admin_feedback,
  human_review_status,
  memory_destination,
  original_draft,
  edited_lesson,
  reviewed_by,
  reviewed_at,
  created_at
from public.source_lessons;


-- Verification: required work_type columns used by Shelter Prep migrations.
DO $$
DECLARE
  required_columns text[][] := ARRAY[
    ARRAY['leads', 'work_type'],
    ARRAY['work_requests', 'work_type'],
    ARRAY['source_lessons', 'work_type'],
    ARRAY['human_pricing_memory', 'work_type'],
    ARRAY['seller_prep_rules', 'work_type'],
    ARRAY['seller_prep_local_cost_stats', 'work_type'],
    ARRAY['job_execution_step_learning', 'work_type'],
    ARRAY['pricing_memory_entries', 'work_type']
  ];
  pair text[];
BEGIN
  FOREACH pair SLICE 1 IN ARRAY required_columns LOOP
    IF to_regclass(format('public.%I', pair[1])) IS NOT NULL AND NOT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = pair[1]
        AND column_name = pair[2]
    ) THEN
      RAISE EXCEPTION 'Required column public.%.% is missing', pair[1], pair[2];
    END IF;
  END LOOP;
END $$;
