-- Shelter Prep real file-storage spine.
-- Scope: private Supabase Storage bucket, durable file metadata, signed access
-- audit events, and compatibility with the existing leads-based request flow.

begin;

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Canonical property/request columns used by the storage spine.
-- ---------------------------------------------------------------------------

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  address text not null default 'Unknown address',
  city text,
  state text,
  zip text,
  status text not null default 'active'
);

alter table public.properties
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists address text not null default 'Unknown address',
  add column if not exists city text,
  add column if not exists state text,
  add column if not exists zip text,
  add column if not exists status text not null default 'active';

create table if not exists public.work_requests (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  property_id bigint references public.properties(id) on delete set null,
  requester_name text,
  requester_email text,
  requester_phone text,
  work_type text,
  description text,
  urgency text,
  occupancy text,
  status text not null default 'new'
);

alter table public.work_requests
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists property_id bigint,
  add column if not exists lead_id uuid,
  add column if not exists requester_name text,
  add column if not exists requester_email text,
  add column if not exists requester_phone text,
  add column if not exists work_type text,
  add column if not exists request_type text,
  add column if not exists description text,
  add column if not exists urgency text,
  add column if not exists occupancy text,
  add column if not exists status text not null default 'new',
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists created_by uuid,
  add column if not exists metadata jsonb not null default '{}'::jsonb;

create index if not exists work_requests_property_id_idx on public.work_requests(property_id);
create index if not exists work_requests_lead_id_idx on public.work_requests(lead_id);
create index if not exists work_requests_created_at_idx on public.work_requests(created_at desc);

-- ---------------------------------------------------------------------------
-- Private bucket and file metadata.
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public)
values ('shelter-prep-files', 'shelter-prep-files', false)
on conflict (id) do update
set public = false;

-- Keep legacy buckets private and remove the old public/anon read path.
insert into storage.buckets (id, name, public)
values ('job-files', 'job-files', false)
on conflict (id) do update
set public = false;

drop policy if exists "job files anon read public urls" on storage.objects;
drop policy if exists "job files anon upload" on storage.objects;

create table if not exists public.files (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  property_id bigint,
  work_request_id uuid,
  lead_id uuid,
  original_name text,
  file_name text,
  file_url text,
  storage_bucket text not null default 'shelter-prep-files',
  storage_path text,
  mime_type text,
  file_size bigint,
  uploaded_by uuid,
  file_kind text,
  file_type text,
  review_status text not null default 'needs_review'
);

alter table public.files
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists property_id bigint,
  add column if not exists work_request_id uuid,
  add column if not exists lead_id uuid,
  add column if not exists linked_property_id bigint,
  add column if not exists linked_work_request_id uuid,
  add column if not exists linked_request_id text,
  add column if not exists linked_lead_id text,
  add column if not exists original_name text,
  add column if not exists original_filename text,
  add column if not exists file_name text,
  add column if not exists file_url text,
  add column if not exists storage_bucket text not null default 'shelter-prep-files',
  add column if not exists bucket text,
  add column if not exists storage_path text,
  add column if not exists mime_type text,
  add column if not exists file_size bigint,
  add column if not exists size_bytes bigint,
  add column if not exists uploaded_by uuid,
  add column if not exists file_kind text,
  add column if not exists file_type text,
  add column if not exists review_status text not null default 'needs_review',
  add column if not exists visibility text not null default 'private',
  add column if not exists metadata jsonb not null default '{}'::jsonb;

update public.files
set
  storage_bucket = coalesce(nullif(storage_bucket, ''), bucket, 'shelter-prep-files'),
  bucket = coalesce(nullif(bucket, ''), nullif(storage_bucket, ''), 'shelter-prep-files'),
  original_name = coalesce(nullif(original_name, ''), nullif(original_filename, ''), nullif(file_name, ''), 'Uploaded file'),
  original_filename = coalesce(nullif(original_filename, ''), nullif(original_name, ''), nullif(file_name, ''), 'Uploaded file'),
  size_bytes = coalesce(size_bytes, file_size::bigint),
  file_kind = coalesce(nullif(file_kind, ''), nullif(file_type, ''), 'document'),
  file_type = coalesce(nullif(file_type, ''), nullif(file_kind, ''), 'document'),
  review_status = coalesce(nullif(review_status, ''), 'needs_review'),
  visibility = coalesce(nullif(visibility, ''), 'private');

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.files'::regclass
      and conname = 'files_review_status_spine_check'
  ) then
    alter table public.files
      add constraint files_review_status_spine_check
      check (review_status in ('needs_review', 'uploaded', 'reviewed', 'approved', 'rejected', 'deprecated'))
      not valid;
  end if;
end $$;

create index if not exists files_property_id_idx on public.files(property_id);
create index if not exists files_work_request_id_idx on public.files(work_request_id);
create index if not exists files_lead_id_idx on public.files(lead_id);
create index if not exists files_storage_location_idx on public.files(storage_bucket, storage_path);
create index if not exists files_created_at_idx on public.files(created_at desc);

alter table public.files enable row level security;

drop policy if exists "shelter prep files read" on public.files;
create policy "shelter prep files read"
on public.files
for select
to authenticated
using (
  public.current_user_role() in ('admin', 'owner', 'estimator', 'agent')
  or uploaded_by = auth.uid()
);

drop policy if exists "shelter prep files insert" on public.files;
create policy "shelter prep files insert"
on public.files
for insert
to anon, authenticated
with check (
  coalesce(storage_bucket, 'shelter-prep-files') in ('shelter-prep-files', 'job-files')
  and coalesce(storage_path, '') <> ''
  and coalesce(review_status, 'needs_review') = 'needs_review'
);

drop policy if exists "shelter prep files admin update" on public.files;
create policy "shelter prep files admin update"
on public.files
for update
to authenticated
using (public.is_admin_or_owner())
with check (public.is_admin_or_owner());

drop policy if exists "shelter prep storage intake upload" on storage.objects;
create policy "shelter prep storage intake upload"
on storage.objects
for insert
to anon, authenticated
with check (bucket_id = 'shelter-prep-files');

drop policy if exists "shelter prep storage signed read" on storage.objects;
create policy "shelter prep storage signed read"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'shelter-prep-files'
  and (
    public.current_user_role() in ('admin', 'owner', 'estimator', 'agent')
    or exists (
      select 1
      from public.files f
      where f.storage_bucket = storage.objects.bucket_id
        and f.storage_path = storage.objects.name
        and f.uploaded_by = auth.uid()
    )
  )
);

drop policy if exists "shelter prep storage admin delete" on storage.objects;
create policy "shelter prep storage admin delete"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'shelter-prep-files'
  and public.is_admin_or_owner()
);

-- ---------------------------------------------------------------------------
-- Signed URL/access audit trail.
-- ---------------------------------------------------------------------------

create table if not exists public.file_access_events (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  file_id uuid,
  work_request_id uuid,
  actor_id uuid,
  action text,
  signed_url_created boolean not null default false
);

alter table public.file_access_events
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists file_id uuid,
  add column if not exists work_request_id uuid,
  add column if not exists actor_id uuid,
  add column if not exists user_id uuid,
  add column if not exists accessed_by uuid,
  add column if not exists action text,
  add column if not exists access_type text,
  add column if not exists signed_url_created boolean not null default false,
  add column if not exists metadata jsonb not null default '{}'::jsonb;

create index if not exists file_access_events_file_id_idx on public.file_access_events(file_id);
create index if not exists file_access_events_work_request_id_idx on public.file_access_events(work_request_id);
create index if not exists file_access_events_actor_id_idx on public.file_access_events(actor_id);
create index if not exists file_access_events_action_idx on public.file_access_events(action);
create index if not exists file_access_events_created_at_idx on public.file_access_events(created_at desc);

alter table public.file_access_events enable row level security;

drop policy if exists "file access events insert own" on public.file_access_events;
create policy "file access events insert own"
on public.file_access_events
for insert
to authenticated
with check (
  public.is_admin_or_owner()
  or actor_id = auth.uid()
  or user_id = auth.uid()
  or accessed_by = auth.uid()
);

drop policy if exists "file access events admin read" on public.file_access_events;
create policy "file access events admin read"
on public.file_access_events
for select
to authenticated
using (public.is_admin_or_owner());

notify pgrst, 'reload schema';

commit;
