-- Phase 1 Step 3: canonical property-centered schema.
-- Migration file only. Do not apply until it has been reviewed by a human.
-- Scope: Property -> Work Request -> Files -> Repair Items -> Review -> Report.
-- This migration intentionally does not add storage buckets, policies, or RLS.

begin;

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Shared helpers
-- ---------------------------------------------------------------------------

create or replace function public.phase1_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.phase1_prevent_workflow_event_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception 'workflow_events are immutable and may only be inserted';
end;
$$;

-- ---------------------------------------------------------------------------
-- properties
-- ---------------------------------------------------------------------------

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by text,
  address text not null default 'Unknown address',
  canonical_address text,
  street_line_1 text,
  street_line_2 text,
  city text,
  state text,
  zip text,
  zip4 text,
  property_type text,
  year_built text,
  square_feet text,
  bedrooms text,
  bathrooms text,
  lot_size text,
  parcel_number text,
  jurisdiction text,
  zoning text,
  status text not null default 'active',
  needs_review boolean not null default false,
  review_reason text,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  constraint properties_status_check
    check (status in ('active', 'archived', 'blocked'))
);

alter table public.properties
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists created_by text,
  add column if not exists address text not null default 'Unknown address',
  add column if not exists canonical_address text,
  add column if not exists street_line_1 text,
  add column if not exists street_line_2 text,
  add column if not exists city text,
  add column if not exists state text,
  add column if not exists zip text,
  add column if not exists zip4 text,
  add column if not exists property_type text,
  add column if not exists year_built text,
  add column if not exists square_feet text,
  add column if not exists bedrooms text,
  add column if not exists bathrooms text,
  add column if not exists lot_size text,
  add column if not exists parcel_number text,
  add column if not exists jurisdiction text,
  add column if not exists zoning text,
  add column if not exists status text not null default 'active',
  add column if not exists needs_review boolean not null default false,
  add column if not exists review_reason text,
  add column if not exists notes text,
  add column if not exists metadata jsonb not null default '{}'::jsonb;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.properties'::regclass
      and conname = 'properties_status_check'
  ) then
    alter table public.properties
      add constraint properties_status_check
      check (status in ('active', 'archived', 'blocked'))
      not valid;
  end if;
end $$;

create index if not exists properties_canonical_address_idx
  on public.properties(canonical_address)
  where canonical_address is not null;
create index if not exists properties_status_idx on public.properties(status);
create index if not exists properties_zip_idx on public.properties(zip);
create index if not exists properties_needs_review_idx on public.properties(needs_review) where needs_review = true;

drop trigger if exists phase1_touch_properties_updated_at on public.properties;
create trigger phase1_touch_properties_updated_at
before update on public.properties
for each row execute function public.phase1_set_updated_at();

-- ---------------------------------------------------------------------------
-- work_requests
-- ---------------------------------------------------------------------------

create table if not exists public.work_requests (
  id uuid primary key default gen_random_uuid(),
  property_id bigint not null references public.properties(id) on delete cascade,
  title text not null default 'Untitled request',
  request_type text not null default 'intake',
  description text,
  status text not null default 'draft',
  priority text not null default 'normal',
  intake_source text,
  requested_by uuid references auth.users(id) on delete set null,
  assigned_to uuid references auth.users(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  submitted_at timestamptz,
  completed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  constraint work_requests_status_check
    check (status in ('draft', 'new', 'intake', 'in_review', 'ready', 'blocked', 'completed', 'archived')),
  constraint work_requests_priority_check
    check (priority in ('low', 'normal', 'high', 'urgent'))
);

alter table public.work_requests
  add column if not exists property_id bigint,
  add column if not exists title text not null default 'Untitled request',
  add column if not exists request_type text not null default 'intake',
  add column if not exists description text,
  add column if not exists status text not null default 'draft',
  add column if not exists priority text not null default 'normal',
  add column if not exists intake_source text,
  add column if not exists requested_by uuid,
  add column if not exists assigned_to uuid,
  add column if not exists created_by uuid,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists submitted_at timestamptz,
  add column if not exists completed_at timestamptz,
  add column if not exists metadata jsonb not null default '{}'::jsonb;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.work_requests'::regclass
      and conname = 'work_requests_property_id_fkey'
  ) then
    alter table public.work_requests
      add constraint work_requests_property_id_fkey
      foreign key (property_id) references public.properties(id) on delete cascade
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.work_requests'::regclass
      and conname = 'work_requests_status_check'
  ) then
    alter table public.work_requests
      add constraint work_requests_status_check
      check (status in ('draft', 'new', 'intake', 'in_review', 'ready', 'blocked', 'completed', 'archived'))
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.work_requests'::regclass
      and conname = 'work_requests_priority_check'
  ) then
    alter table public.work_requests
      add constraint work_requests_priority_check
      check (priority in ('low', 'normal', 'high', 'urgent'))
      not valid;
  end if;
end $$;

create index if not exists work_requests_property_id_idx on public.work_requests(property_id);
create index if not exists work_requests_status_idx on public.work_requests(status);
create index if not exists work_requests_created_at_idx on public.work_requests(created_at desc);

drop trigger if exists phase1_touch_work_requests_updated_at on public.work_requests;
create trigger phase1_touch_work_requests_updated_at
before update on public.work_requests
for each row execute function public.phase1_set_updated_at();

-- ---------------------------------------------------------------------------
-- files
-- Permanent file metadata only. Runtime URL values are generated later and
-- tracked through file_access_events.
-- ---------------------------------------------------------------------------

create table if not exists public.files (
  id uuid primary key default gen_random_uuid(),
  work_request_id uuid not null references public.work_requests(id) on delete cascade,
  storage_bucket text not null,
  storage_path text not null,
  original_name text not null,
  mime_type text,
  size_bytes bigint,
  uploaded_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint files_size_bytes_check
    check (size_bytes is null or size_bytes >= 0)
);

alter table public.files
  add column if not exists work_request_id uuid,
  add column if not exists storage_bucket text,
  add column if not exists storage_path text,
  add column if not exists original_name text,
  add column if not exists mime_type text,
  add column if not exists size_bytes bigint,
  add column if not exists uploaded_by uuid,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists metadata jsonb not null default '{}'::jsonb;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.files'::regclass
      and conname = 'files_work_request_id_fkey'
  ) then
    alter table public.files
      add constraint files_work_request_id_fkey
      foreign key (work_request_id) references public.work_requests(id) on delete cascade
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.files'::regclass
      and conname = 'files_uploaded_by_fkey'
  ) then
    alter table public.files
      add constraint files_uploaded_by_fkey
      foreign key (uploaded_by) references auth.users(id) on delete set null
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.files'::regclass
      and conname = 'files_size_bytes_check'
  ) then
    alter table public.files
      add constraint files_size_bytes_check
      check (size_bytes is null or size_bytes >= 0)
      not valid;
  end if;
end $$;

create index if not exists files_storage_location_idx
  on public.files(storage_bucket, storage_path)
  where storage_bucket is not null and storage_path is not null;
create index if not exists files_work_request_id_idx on public.files(work_request_id);
create index if not exists files_created_at_idx on public.files(created_at desc);

-- ---------------------------------------------------------------------------
-- repair_items
-- ---------------------------------------------------------------------------

create table if not exists public.repair_items (
  id uuid primary key default gen_random_uuid(),
  property_id bigint not null references public.properties(id) on delete cascade,
  work_request_id uuid not null references public.work_requests(id) on delete cascade,
  source_file_id uuid references public.files(id) on delete set null,
  title text not null default 'Untitled repair item',
  description text not null default '',
  location text,
  category text,
  trade text,
  severity text,
  priority text not null default 'normal',
  status text not null default 'draft',
  estimate_low numeric,
  estimate_high numeric,
  confidence text not null default 'low',
  human_review_required boolean not null default true,
  human_reviewed_by uuid references auth.users(id) on delete set null,
  human_reviewed_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint repair_items_priority_check
    check (priority in ('low', 'normal', 'high', 'urgent')),
  constraint repair_items_status_check
    check (status in ('draft', 'needs_review', 'approved', 'rejected', 'completed', 'archived')),
  constraint repair_items_confidence_check
    check (confidence in ('low', 'medium', 'high'))
);

alter table public.repair_items
  add column if not exists property_id bigint,
  add column if not exists work_request_id uuid,
  add column if not exists source_file_id uuid,
  add column if not exists title text not null default 'Untitled repair item',
  add column if not exists description text not null default '',
  add column if not exists location text,
  add column if not exists category text,
  add column if not exists trade text,
  add column if not exists severity text,
  add column if not exists priority text not null default 'normal',
  add column if not exists status text not null default 'draft',
  add column if not exists estimate_low numeric,
  add column if not exists estimate_high numeric,
  add column if not exists confidence text not null default 'low',
  add column if not exists human_review_required boolean not null default true,
  add column if not exists human_reviewed_by uuid,
  add column if not exists human_reviewed_at timestamptz,
  add column if not exists created_by uuid,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists metadata jsonb not null default '{}'::jsonb;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.repair_items'::regclass
      and conname = 'repair_items_property_id_fkey'
  ) then
    alter table public.repair_items
      add constraint repair_items_property_id_fkey
      foreign key (property_id) references public.properties(id) on delete cascade
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.repair_items'::regclass
      and conname = 'repair_items_work_request_id_fkey'
  ) then
    alter table public.repair_items
      add constraint repair_items_work_request_id_fkey
      foreign key (work_request_id) references public.work_requests(id) on delete cascade
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.repair_items'::regclass
      and conname = 'repair_items_source_file_id_fkey'
  ) then
    alter table public.repair_items
      add constraint repair_items_source_file_id_fkey
      foreign key (source_file_id) references public.files(id) on delete set null
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.repair_items'::regclass
      and conname = 'repair_items_priority_check'
  ) then
    alter table public.repair_items
      add constraint repair_items_priority_check
      check (priority in ('low', 'normal', 'high', 'urgent'))
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.repair_items'::regclass
      and conname = 'repair_items_status_check'
  ) then
    alter table public.repair_items
      add constraint repair_items_status_check
      check (status in ('draft', 'needs_review', 'approved', 'rejected', 'completed', 'archived'))
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.repair_items'::regclass
      and conname = 'repair_items_confidence_check'
  ) then
    alter table public.repair_items
      add constraint repair_items_confidence_check
      check (confidence in ('low', 'medium', 'high'))
      not valid;
  end if;
end $$;

create index if not exists repair_items_property_id_idx on public.repair_items(property_id);
create index if not exists repair_items_work_request_id_idx on public.repair_items(work_request_id);
create index if not exists repair_items_status_idx on public.repair_items(status);
create index if not exists repair_items_priority_idx on public.repair_items(priority);

drop trigger if exists phase1_touch_repair_items_updated_at on public.repair_items;
create trigger phase1_touch_repair_items_updated_at
before update on public.repair_items
for each row execute function public.phase1_set_updated_at();

-- ---------------------------------------------------------------------------
-- contractors
-- ---------------------------------------------------------------------------

create table if not exists public.contractors (
  id uuid primary key default gen_random_uuid(),
  company_name text not null,
  contact_name text,
  email text,
  phone text,
  license_number text,
  insurance_status text,
  approval_status text not null default 'pending',
  trades text[] not null default '{}',
  service_areas text[] not null default '{}',
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint contractors_approval_status_check
    check (approval_status in ('pending', 'approved', 'paused', 'rejected', 'archived'))
);

alter table public.contractors
  add column if not exists company_name text,
  add column if not exists contact_name text,
  add column if not exists email text,
  add column if not exists phone text,
  add column if not exists license_number text,
  add column if not exists insurance_status text,
  add column if not exists approval_status text not null default 'pending',
  add column if not exists trades text[] not null default '{}',
  add column if not exists service_areas text[] not null default '{}',
  add column if not exists notes text,
  add column if not exists created_by uuid,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists metadata jsonb not null default '{}'::jsonb;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.contractors'::regclass
      and conname = 'contractors_approval_status_check'
  ) then
    alter table public.contractors
      add constraint contractors_approval_status_check
      check (approval_status in ('pending', 'approved', 'paused', 'rejected', 'archived'))
      not valid;
  end if;
end $$;

create index if not exists contractors_approval_status_idx on public.contractors(approval_status);
create index if not exists contractors_email_idx on public.contractors(email);

drop trigger if exists phase1_touch_contractors_updated_at on public.contractors;
create trigger phase1_touch_contractors_updated_at
before update on public.contractors
for each row execute function public.phase1_set_updated_at();

-- ---------------------------------------------------------------------------
-- contractor_assignments
-- ---------------------------------------------------------------------------

create table if not exists public.contractor_assignments (
  id uuid primary key default gen_random_uuid(),
  property_id bigint not null references public.properties(id) on delete cascade,
  work_request_id uuid not null references public.work_requests(id) on delete cascade,
  repair_item_id uuid references public.repair_items(id) on delete set null,
  contractor_id uuid not null references public.contractors(id) on delete restrict,
  assigned_by uuid references auth.users(id) on delete set null,
  status text not null default 'assigned',
  assignment_notes text,
  contractor_notes text,
  assigned_at timestamptz not null default now(),
  accepted_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint contractor_assignments_status_check
    check (status in ('assigned', 'accepted', 'declined', 'in_progress', 'needs_review', 'completed', 'cancelled'))
);

alter table public.contractor_assignments
  add column if not exists property_id bigint,
  add column if not exists work_request_id uuid,
  add column if not exists repair_item_id uuid,
  add column if not exists contractor_id uuid,
  add column if not exists assigned_by uuid,
  add column if not exists status text not null default 'assigned',
  add column if not exists assignment_notes text,
  add column if not exists contractor_notes text,
  add column if not exists assigned_at timestamptz not null default now(),
  add column if not exists accepted_at timestamptz,
  add column if not exists completed_at timestamptz,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists metadata jsonb not null default '{}'::jsonb;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.contractor_assignments'::regclass
      and conname = 'contractor_assignments_property_id_fkey'
  ) then
    alter table public.contractor_assignments
      add constraint contractor_assignments_property_id_fkey
      foreign key (property_id) references public.properties(id) on delete cascade
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.contractor_assignments'::regclass
      and conname = 'contractor_assignments_work_request_id_fkey'
  ) then
    alter table public.contractor_assignments
      add constraint contractor_assignments_work_request_id_fkey
      foreign key (work_request_id) references public.work_requests(id) on delete cascade
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.contractor_assignments'::regclass
      and conname = 'contractor_assignments_repair_item_id_fkey'
  ) then
    alter table public.contractor_assignments
      add constraint contractor_assignments_repair_item_id_fkey
      foreign key (repair_item_id) references public.repair_items(id) on delete set null
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.contractor_assignments'::regclass
      and conname = 'contractor_assignments_contractor_id_fkey'
  ) then
    alter table public.contractor_assignments
      add constraint contractor_assignments_contractor_id_fkey
      foreign key (contractor_id) references public.contractors(id) on delete restrict
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.contractor_assignments'::regclass
      and conname = 'contractor_assignments_phase1_status_check'
  ) then
    alter table public.contractor_assignments
      add constraint contractor_assignments_phase1_status_check
      check (status in ('assigned', 'accepted', 'declined', 'in_progress', 'needs_review', 'completed', 'cancelled'))
      not valid;
  end if;
end $$;

create index if not exists contractor_assignments_property_id_idx on public.contractor_assignments(property_id);
create index if not exists contractor_assignments_work_request_id_idx on public.contractor_assignments(work_request_id);
create index if not exists contractor_assignments_repair_item_id_idx on public.contractor_assignments(repair_item_id);
create index if not exists contractor_assignments_contractor_id_idx on public.contractor_assignments(contractor_id);
create index if not exists contractor_assignments_status_idx on public.contractor_assignments(status);

drop trigger if exists phase1_touch_contractor_assignments_updated_at on public.contractor_assignments;
create trigger phase1_touch_contractor_assignments_updated_at
before update on public.contractor_assignments
for each row execute function public.phase1_set_updated_at();

-- ---------------------------------------------------------------------------
-- review_events
-- ---------------------------------------------------------------------------

create table if not exists public.review_events (
  id uuid primary key default gen_random_uuid(),
  property_id bigint not null references public.properties(id) on delete cascade,
  work_request_id uuid references public.work_requests(id) on delete cascade,
  repair_item_id uuid references public.repair_items(id) on delete set null,
  target_table text,
  target_id uuid,
  review_type text not null default 'human_review',
  decision text not null default 'needs_review',
  reviewer_id uuid references auth.users(id) on delete set null,
  previous_status text,
  next_status text,
  notes text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint review_events_decision_check
    check (decision in ('needs_review', 'approved', 'rejected', 'needs_more_info', 'completed'))
);

alter table public.review_events
  add column if not exists property_id bigint,
  add column if not exists work_request_id uuid,
  add column if not exists repair_item_id uuid,
  add column if not exists target_table text,
  add column if not exists target_id uuid,
  add column if not exists review_type text not null default 'human_review',
  add column if not exists decision text not null default 'needs_review',
  add column if not exists reviewer_id uuid,
  add column if not exists previous_status text,
  add column if not exists next_status text,
  add column if not exists notes text,
  add column if not exists payload jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.review_events'::regclass
      and conname = 'review_events_property_id_fkey'
  ) then
    alter table public.review_events
      add constraint review_events_property_id_fkey
      foreign key (property_id) references public.properties(id) on delete cascade
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.review_events'::regclass
      and conname = 'review_events_work_request_id_fkey'
  ) then
    alter table public.review_events
      add constraint review_events_work_request_id_fkey
      foreign key (work_request_id) references public.work_requests(id) on delete cascade
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.review_events'::regclass
      and conname = 'review_events_repair_item_id_fkey'
  ) then
    alter table public.review_events
      add constraint review_events_repair_item_id_fkey
      foreign key (repair_item_id) references public.repair_items(id) on delete set null
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.review_events'::regclass
      and conname = 'review_events_decision_check'
  ) then
    alter table public.review_events
      add constraint review_events_decision_check
      check (decision in ('needs_review', 'approved', 'rejected', 'needs_more_info', 'completed'))
      not valid;
  end if;
end $$;

create index if not exists review_events_property_id_idx on public.review_events(property_id);
create index if not exists review_events_work_request_id_idx on public.review_events(work_request_id);
create index if not exists review_events_repair_item_id_idx on public.review_events(repair_item_id);
create index if not exists review_events_created_at_idx on public.review_events(created_at desc);

-- ---------------------------------------------------------------------------
-- workflow_events
-- Immutable event log.
-- ---------------------------------------------------------------------------

create table if not exists public.workflow_events (
  id uuid primary key default gen_random_uuid(),
  property_id bigint not null references public.properties(id) on delete cascade,
  work_request_id uuid references public.work_requests(id) on delete cascade,
  repair_item_id uuid references public.repair_items(id) on delete set null,
  event_type text not null,
  from_status text,
  to_status text,
  actor_type text not null default 'admin',
  actor_id uuid references auth.users(id) on delete set null,
  reason text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint workflow_events_actor_type_check
    check (actor_type in ('admin', 'human', 'agent', 'system'))
);

alter table public.workflow_events
  add column if not exists property_id bigint,
  add column if not exists work_request_id uuid,
  add column if not exists repair_item_id uuid,
  add column if not exists event_type text,
  add column if not exists from_status text,
  add column if not exists to_status text,
  add column if not exists actor_type text not null default 'admin',
  add column if not exists actor_id uuid,
  add column if not exists reason text,
  add column if not exists payload jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.workflow_events'::regclass
      and conname = 'workflow_events_property_id_fkey'
  ) then
    alter table public.workflow_events
      add constraint workflow_events_property_id_fkey
      foreign key (property_id) references public.properties(id) on delete cascade
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.workflow_events'::regclass
      and conname = 'workflow_events_work_request_id_fkey'
  ) then
    alter table public.workflow_events
      add constraint workflow_events_work_request_id_fkey
      foreign key (work_request_id) references public.work_requests(id) on delete cascade
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.workflow_events'::regclass
      and conname = 'workflow_events_repair_item_id_fkey'
  ) then
    alter table public.workflow_events
      add constraint workflow_events_repair_item_id_fkey
      foreign key (repair_item_id) references public.repair_items(id) on delete set null
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.workflow_events'::regclass
      and conname = 'workflow_events_actor_type_check'
  ) then
    alter table public.workflow_events
      add constraint workflow_events_actor_type_check
      check (actor_type in ('admin', 'human', 'agent', 'system'))
      not valid;
  end if;
end $$;

create index if not exists workflow_events_property_id_idx on public.workflow_events(property_id);
create index if not exists workflow_events_work_request_id_idx on public.workflow_events(work_request_id);
create index if not exists workflow_events_repair_item_id_idx on public.workflow_events(repair_item_id);
create index if not exists workflow_events_event_type_idx on public.workflow_events(event_type);
create index if not exists workflow_events_created_at_idx on public.workflow_events(created_at desc);

drop trigger if exists phase1_block_workflow_events_update on public.workflow_events;
create trigger phase1_block_workflow_events_update
before update on public.workflow_events
for each row execute function public.phase1_prevent_workflow_event_mutation();

drop trigger if exists phase1_block_workflow_events_delete on public.workflow_events;
create trigger phase1_block_workflow_events_delete
before delete on public.workflow_events
for each row execute function public.phase1_prevent_workflow_event_mutation();

-- ---------------------------------------------------------------------------
-- agents
-- Registry only. No rows are inserted and no agent behavior is enabled here.
-- ---------------------------------------------------------------------------

create table if not exists public.agents (
  id uuid primary key default gen_random_uuid(),
  agent_key text not null unique,
  display_name text not null,
  status text not null default 'inactive',
  human_review_required boolean not null default true,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint agents_agent_key_check
    check (agent_key in ('intake', 'inspector', 'gap_detection', 'scope_drafter', 'report', 'ux_presentation')),
  constraint agents_status_check
    check (status in ('inactive', 'available', 'paused', 'retired'))
);

alter table public.agents
  add column if not exists agent_key text,
  add column if not exists display_name text,
  add column if not exists status text not null default 'inactive',
  add column if not exists human_review_required boolean not null default true,
  add column if not exists description text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists metadata jsonb not null default '{}'::jsonb;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.agents'::regclass
      and conname = 'agents_agent_key_check'
  ) then
    alter table public.agents
      add constraint agents_agent_key_check
      check (agent_key in ('intake', 'inspector', 'gap_detection', 'scope_drafter', 'report', 'ux_presentation'))
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.agents'::regclass
      and conname = 'agents_status_check'
  ) then
    alter table public.agents
      add constraint agents_status_check
      check (status in ('inactive', 'available', 'paused', 'retired'))
      not valid;
  end if;
end $$;

create index if not exists agents_agent_key_idx on public.agents(agent_key);
create index if not exists agents_status_idx on public.agents(status);

drop trigger if exists phase1_touch_agents_updated_at on public.agents;
create trigger phase1_touch_agents_updated_at
before update on public.agents
for each row execute function public.phase1_set_updated_at();

-- ---------------------------------------------------------------------------
-- file_access_events
-- URL/access lifecycle tracking for file views and downloads.
-- ---------------------------------------------------------------------------

create table if not exists public.file_access_events (
  id uuid primary key default gen_random_uuid(),
  file_id uuid not null references public.files(id) on delete cascade,
  work_request_id uuid references public.work_requests(id) on delete cascade,
  access_type text not null,
  accessed_by uuid references auth.users(id) on delete set null,
  access_purpose text,
  ip_address inet,
  user_agent text,
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint file_access_events_access_type_check
    check (access_type in ('requested', 'created', 'viewed', 'downloaded', 'expired', 'revoked'))
);

alter table public.file_access_events
  add column if not exists file_id uuid,
  add column if not exists work_request_id uuid,
  add column if not exists access_type text,
  add column if not exists accessed_by uuid,
  add column if not exists access_purpose text,
  add column if not exists ip_address inet,
  add column if not exists user_agent text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists metadata jsonb not null default '{}'::jsonb;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.file_access_events'::regclass
      and conname = 'file_access_events_file_id_fkey'
  ) then
    alter table public.file_access_events
      add constraint file_access_events_file_id_fkey
      foreign key (file_id) references public.files(id) on delete cascade
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.file_access_events'::regclass
      and conname = 'file_access_events_work_request_id_fkey'
  ) then
    alter table public.file_access_events
      add constraint file_access_events_work_request_id_fkey
      foreign key (work_request_id) references public.work_requests(id) on delete cascade
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.file_access_events'::regclass
      and conname = 'file_access_events_accessed_by_fkey'
  ) then
    alter table public.file_access_events
      add constraint file_access_events_accessed_by_fkey
      foreign key (accessed_by) references auth.users(id) on delete set null
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.file_access_events'::regclass
      and conname = 'file_access_events_access_type_check'
  ) then
    alter table public.file_access_events
      add constraint file_access_events_access_type_check
      check (access_type in ('requested', 'created', 'viewed', 'downloaded', 'expired', 'revoked'))
      not valid;
  end if;
end $$;

create index if not exists file_access_events_file_id_idx on public.file_access_events(file_id);
create index if not exists file_access_events_work_request_id_idx on public.file_access_events(work_request_id);
create index if not exists file_access_events_access_type_idx on public.file_access_events(access_type);
create index if not exists file_access_events_created_at_idx on public.file_access_events(created_at desc);

-- ---------------------------------------------------------------------------
-- agent_tasks
-- Admin/human/agent task queue only. This is not online research automation.
-- ---------------------------------------------------------------------------

create table if not exists public.agent_tasks (
  id uuid primary key default gen_random_uuid(),
  property_id bigint not null references public.properties(id) on delete cascade,
  work_request_id uuid not null references public.work_requests(id) on delete cascade,
  repair_item_id uuid references public.repair_items(id) on delete set null,
  task_type text not null,
  title text not null,
  question text,
  assigned_to_type text not null default 'admin',
  assigned_agent text not null default 'none',
  status text not null default 'draft',
  priority text not null default 'normal',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  result_summary text,
  human_review_required boolean not null default true,
  human_reviewed_by uuid references auth.users(id) on delete set null,
  human_reviewed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  constraint agent_tasks_assigned_to_type_check
    check (assigned_to_type in ('admin', 'human', 'agent')),
  constraint agent_tasks_assigned_agent_check
    check (assigned_agent in ('intake', 'inspector', 'gap_detection', 'scope_drafter', 'report', 'ux_presentation', 'none')),
  constraint agent_tasks_status_check
    check (status in ('draft', 'queued', 'in_progress', 'needs_review', 'approved', 'rejected', 'completed')),
  constraint agent_tasks_priority_check
    check (priority in ('low', 'normal', 'high', 'urgent'))
);

alter table public.agent_tasks
  add column if not exists property_id bigint,
  add column if not exists work_request_id uuid,
  add column if not exists repair_item_id uuid,
  add column if not exists task_type text,
  add column if not exists title text,
  add column if not exists question text,
  add column if not exists assigned_to_type text not null default 'admin',
  add column if not exists assigned_agent text not null default 'none',
  add column if not exists status text not null default 'draft',
  add column if not exists priority text not null default 'normal',
  add column if not exists created_by uuid,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists completed_at timestamptz,
  add column if not exists result_summary text,
  add column if not exists human_review_required boolean not null default true,
  add column if not exists human_reviewed_by uuid,
  add column if not exists human_reviewed_at timestamptz,
  add column if not exists metadata jsonb not null default '{}'::jsonb;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.agent_tasks'::regclass
      and conname = 'agent_tasks_property_id_fkey'
  ) then
    alter table public.agent_tasks
      add constraint agent_tasks_property_id_fkey
      foreign key (property_id) references public.properties(id) on delete cascade
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.agent_tasks'::regclass
      and conname = 'agent_tasks_work_request_id_fkey'
  ) then
    alter table public.agent_tasks
      add constraint agent_tasks_work_request_id_fkey
      foreign key (work_request_id) references public.work_requests(id) on delete cascade
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.agent_tasks'::regclass
      and conname = 'agent_tasks_repair_item_id_fkey'
  ) then
    alter table public.agent_tasks
      add constraint agent_tasks_repair_item_id_fkey
      foreign key (repair_item_id) references public.repair_items(id) on delete set null
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.agent_tasks'::regclass
      and conname = 'agent_tasks_assigned_to_type_check'
  ) then
    alter table public.agent_tasks
      add constraint agent_tasks_assigned_to_type_check
      check (assigned_to_type in ('admin', 'human', 'agent'))
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.agent_tasks'::regclass
      and conname = 'agent_tasks_assigned_agent_check'
  ) then
    alter table public.agent_tasks
      add constraint agent_tasks_assigned_agent_check
      check (assigned_agent in ('intake', 'inspector', 'gap_detection', 'scope_drafter', 'report', 'ux_presentation', 'none'))
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.agent_tasks'::regclass
      and conname = 'agent_tasks_status_check'
  ) then
    alter table public.agent_tasks
      add constraint agent_tasks_status_check
      check (status in ('draft', 'queued', 'in_progress', 'needs_review', 'approved', 'rejected', 'completed'))
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.agent_tasks'::regclass
      and conname = 'agent_tasks_priority_check'
  ) then
    alter table public.agent_tasks
      add constraint agent_tasks_priority_check
      check (priority in ('low', 'normal', 'high', 'urgent'))
      not valid;
  end if;
end $$;

create index if not exists agent_tasks_property_id_idx on public.agent_tasks(property_id);
create index if not exists agent_tasks_work_request_id_idx on public.agent_tasks(work_request_id);
create index if not exists agent_tasks_repair_item_id_idx on public.agent_tasks(repair_item_id);
create index if not exists agent_tasks_assigned_to_type_idx on public.agent_tasks(assigned_to_type);
create index if not exists agent_tasks_assigned_agent_idx on public.agent_tasks(assigned_agent);
create index if not exists agent_tasks_status_idx on public.agent_tasks(status);
create index if not exists agent_tasks_priority_idx on public.agent_tasks(priority);
create index if not exists agent_tasks_created_at_idx on public.agent_tasks(created_at desc);

commit;

/*
Manual rollback plan for human review only:

begin;
drop trigger if exists phase1_block_workflow_events_delete on public.workflow_events;
drop trigger if exists phase1_block_workflow_events_update on public.workflow_events;
drop trigger if exists phase1_touch_agents_updated_at on public.agents;
drop trigger if exists phase1_touch_contractor_assignments_updated_at on public.contractor_assignments;
drop trigger if exists phase1_touch_contractors_updated_at on public.contractors;
drop trigger if exists phase1_touch_repair_items_updated_at on public.repair_items;
drop trigger if exists phase1_touch_work_requests_updated_at on public.work_requests;
drop trigger if exists phase1_touch_properties_updated_at on public.properties;
drop table if exists public.agent_tasks;
drop table if exists public.file_access_events;
drop table if exists public.agents;
drop table if exists public.workflow_events;
drop table if exists public.review_events;
drop table if exists public.contractor_assignments;
drop table if exists public.contractors;
drop table if exists public.repair_items;
drop table if exists public.files;
drop table if exists public.work_requests;
drop table if exists public.properties;
drop function if exists public.phase1_prevent_workflow_event_mutation();
drop function if exists public.phase1_set_updated_at();
commit;

Before using this rollback, confirm no production data depends on these tables.
*/
